// Generated by scripts/exp1_typst.py -- do not edit by hand.
#figure(
  table(
    columns: 8,
    align: (left, left, right, right, right, right, right, right),
    stroke: none,
    inset: (x: 2.5pt, y: 4pt),
    table.hline(stroke: 0.8pt),
    table.header(
      table.cell(rowspan: 2)[*Dataset*], table.cell(rowspan: 2)[*Geom.*], table.cell(colspan: 2)[*Wilson fit*], table.cell(colspan: 4)[*Pareto front*],
      [$rho$], [$kappa$], [$R_2$], [$Delta R_2$], [$tilde(kappa)$], [$n_"front"$],
    ),
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[grid\ #text(size: 0.8em)[(euclidean)]], [sph], [$0.116$#super[†]], [$5.81$#super[†]], [$8.73 dot 10^(-3)$], [$+0.0012$], [$2.57$], [$147$],
    [*euc*], [$0.127$], [$0$], [$9.90 dot 10^(-3)$], [---], [$0$], [$163$],
    [hyp], [$0.130$#super[†]], [$0.0100$#super[†]], [$9.50 dot 10^(-3)$], [$+0.0004$], [$0.0232$], [$179$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[sphere\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.0851$], [$2.99$], [$0.149$], [$+0.0126$], [$2.94$], [$361$],
    [euc], [$0.277$], [$0$], [$0.161$], [---], [$0$], [$176$],
    [hyp], [$0.284$#super[†]], [$0.0100$#super[†]], [$0.157$], [$+0.0044$], [$3.41 dot 10^(-3)$], [$309$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[antipodal\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.0219$], [$4.22$], [$0.0459$], [$+0.0043$], [$2.47$], [$239$],
    [euc], [$0.142$], [$0$], [$0.0502$], [---], [$0$], [$225$],
    [hyp], [$0.144$#super[†]], [$0.0100$#super[†]], [$0.0470$], [$+0.0032$], [$0.0437$], [$258$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[tree\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.0625$], [$5.73$], [$0.0546$], [$+0.0083$], [$2.47$], [$380$],
    [euc], [$0.0673$], [$0$], [$0.0629$], [---], [$0$], [$244$],
    [*hyp*], [$0.0675$#super[†]], [$0.0100$#super[†]], [$0.0458$], [$+0.0172$], [$1.54$], [$387$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[hyp. shells\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.0632$], [$7.77$], [$0.125$], [$+0.0195$], [$2.47$], [$604$],
    [euc], [$0.0701$], [$0$], [$0.144$], [---], [$0$], [$456$],
    [*hyp*], [$0.0711$#super[†]], [$0.0100$#super[†]], [$0.123$], [$+0.0206$], [$4.43 dot 10^(-5)$], [$554$],
    table.hline(stroke: 0.8pt),
  ),
  caption: [Experiment 1: matched embedding geometry against the Euclidean baseline,
  on the synthetic datasets of known intrinsic geometry ($N = 5000$, `all_off`,
  preference region $W_"all"$).
  Each dataset is embedded under all three geometries; the row whose geometry matches
  the data's intrinsic curvature sign is set in bold.

  $R_2$ is the R2 indicator of the cell's Pareto front (@eq:r2), a *cost*: smaller is
  better.  $Delta R_2 = R_2("euc") - R_2("geom")$ is therefore formed baseline-minus-row,
  so a positive value means the row's geometry improved on the Euclidean baseline ---
  the same reading direction as @eq:r2-gain.
  $n_"front"$ is the front's size, reported because $R_2$ improves monotonically
  with it: fronts here range over an order of magnitude, and the Euclidean fronts are
  consistently among the smallest, which biases $Delta R_2$ *toward* the curved arms.

  Both $kappa$ columns are the same quantity, $|K| dot R_"rms"^2$ of @eq:kappa: the
  Wilson arm's is measured on the configuration its fit implies, $tilde(kappa)$ is the
  median over the front.  They share a gauge, so the pair reads as a comparison ---
  what the detector infers about the data against what the optimiser actually chose.
  Both are $0$ for the Euclidean arm, where $K = 0$ exactly.

  The Wilson columns bring the curvature detector into the same objective space.
  Each arm of @tab:geometry-inference fits a constant-curvature Gram matrix $Z(r)$ to
  the data; because that $Z$ *is* the Gram matrix of the model it tests for, its
  retained eigen-block is an embedding.  Reconstructing it and scoring it with the
  same metric code every t-SNE trial goes through puts the fit at a single point $w$ of
  the ten-objective space, so it can be compared with the front rather than merely set
  beside it.
  $rho$ is that arm's normalised signature residual, gauged by $n dot d_"max"^2$;
  it is also exactly the eigenvalue mass the reconstruction discarded, so it is the
  reconstruction's own error and not a separate misfit score.

  A dagger marks a fit pinned on the flat-ward edge of its search window, where the
  reported value is the bound and not a measurement.  The hyperbolic search is capped
  at the radius where $kappa$ falls to $0.01$, so a pinned hyperbolic arm reports
  exactly that --- the cap is a bound on the same $kappa$ the column shows.  Every
  hyperbolic arm here is pinned, so no hyperbolic reconstruction in this table is
  meaningfully curved: the column tests the Euclidean null rather than a hyperbolic
  alternative, which is why its $rho$ tracks the Euclidean arm's so closely.

  The Wilson fits are run at $N = 1000$ only --- the radius search is $O(n^3)$
  per candidate radius --- so $rho$ and $kappa$ are carried over, both being
  dimensionless by construction, while the columns comparing the Wilson point
  against the front are omitted: that comparison would set a reconstruction of one
  sample against a front built from another.
  ],
) <tab:geometry-match>
