// Generated by scripts/exp1_r2_typst.py -- do not edit by hand.
#figure(
  table(
    columns: 6,
    align: (left, left, right, right, right, right),
    stroke: none,
    inset: (x: 2.5pt, y: 4pt),
    table.hline(stroke: 0.8pt),
    table.header(
      [*Dataset*], [*Geom.*], [$R_2$], [$Delta R_2$], [$tilde(kappa)$], [$n_"front"$],
    ),
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[grid\ #text(size: 0.8em)[(euclidean)]], [sph], [$0.0174$], [$+0.0020$], [$2.50$], [$166$],
    [*euc*], [$0.0194$], [---], [$0$], [$344$],
    [hyp], [$0.0170$], [$+0.0023$], [$0.135$], [$126$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[sphere\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.150$], [$+0.0124$], [$2.47$], [$289$],
    [euc], [$0.163$], [---], [$0$], [$255$],
    [hyp], [$0.155$], [$+0.0076$], [$0.578$], [$357$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[antipodal\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.0502$], [$+0.0037$], [$2.47$], [$226$],
    [euc], [$0.0539$], [---], [$0$], [$46$],
    [hyp], [$0.0519$], [$+0.0020$], [$0.202$], [$127$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[tree\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.0786$], [$+0.0023$], [$2.47$], [$203$],
    [euc], [$0.0809$], [---], [$0$], [$146$],
    [*hyp*], [$0.0577$], [$+0.0232$], [$13.1$], [$524$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[hyp. shells\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.135$], [$+0.0333$], [$2.47$], [$365$],
    [euc], [$0.168$], [---], [$0$], [$241$],
    [*hyp*], [$0.127$], [$+0.0406$], [$3.95 dot 10^(-6)$], [$580$],
    table.hline(stroke: 0.8pt),
  ),
  caption: [Experiment 1: matched embedding geometry against the Euclidean baseline,
  on the synthetic datasets of known intrinsic geometry ($N = 1000$, `all_off`,
  preference region $W_"all"$).
  Each dataset is embedded under all three geometries; the row whose geometry matches
  the data's intrinsic curvature sign is set in bold.

  $R_2$ is the R2 indicator of the cell's Pareto front (@eq:r2), a *cost*: smaller is
  better.  $Delta R_2 = R_2("euc") - R_2("geom")$ is therefore formed baseline-minus-row,
  so a positive value means the row's geometry improved on the Euclidean baseline ---
  the same reading direction as @eq:r2-gain.
  $n_"front"$ is the front's size, reported because $R_2$ improves monotonically
  with it: fronts here range over an order of magnitude, and the Euclidean fronts are
  consistently among the smallest, which biases $Delta R_2$ *toward* the curved arms.

  $tilde(kappa)$ is the median $|K| dot R_"rms"^2$ of @eq:kappa over the front --- what
  the optimiser actually chose.  It shares its gauge with the $kappa$ the detector infers
  in @tab:wilson-fit, so the two columns may be set side by side.  Both are $0$ for the
  Euclidean arm, where $K = 0$ exactly.
  ],
) <tab:geometry-match-r2>
