// Generated by scripts/exp1_r2_typst.py -- do not edit by hand.
#figure(
  table(
    columns: 6,
    align: (left, left, right, right, right, right),
    stroke: none,
    inset: (x: 2.5pt, y: 4pt),
    table.hline(stroke: 0.8pt),
    table.header(
      [*Dataset*], [*Geom.*], [$R_2$], [$Delta R_2$], [$tilde(kappa)$], [$n_"front"$],
    ),
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[grid\ #text(size: 0.8em)[(euclidean)]], [sph], [$0.153$], [$-0.0275$], [$4.88 dot 10^(-3)$], [$171$],
    [*euc*], [$0.126$], [---], [$0$], [$170$],
    [hyp], [$0.122$], [$+0.0039$], [$0.524$], [$333$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[sphere\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.143$], [$-0.0037$], [$1.36 dot 10^(-4)$], [$222$],
    [euc], [$0.139$], [---], [$0$], [$180$],
    [hyp], [$0.144$], [$-0.0044$], [$0.801$], [$300$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[tree (layout)\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.112$], [$+0.0026$], [$2.97 dot 10^(-3)$], [$363$],
    [euc], [$0.114$], [---], [$0$], [$296$],
    [*hyp*], [$0.114$], [$-0.0000$], [$2.90 dot 10^(-3)$], [$367$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[hyp. shells\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.128$], [$+0.0055$], [$5.18 dot 10^(-5)$], [$344$],
    [euc], [$0.133$], [---], [$0$], [$238$],
    [*hyp*], [$0.126$], [$+0.0069$], [$1.32 dot 10^(-4)$], [$630$],
    table.hline(stroke: 0.8pt),
  ),
  caption: [Experiment 1: matched embedding geometry against the Euclidean baseline,
  on the synthetic datasets of known intrinsic geometry ($N = 5000$, `all_off`,
  preference region $W_"all"$).
  Each dataset is embedded under all three geometries; the row whose geometry matches
  the data's intrinsic curvature sign is set in bold.

  $R_2$ is the R2 indicator of the cell's Pareto front (@eq:r2), a *cost*: smaller is
  better.  $Delta R_2 = R_2("euc") - R_2("geom")$ is therefore formed baseline-minus-row,
  so a positive value means the row's geometry improved on the Euclidean baseline ---
  the same reading direction as @eq:r2-gain.
  $n_"front"$ is the front's size, reported because $R_2$ improves monotonically
  with it: fronts here range over an order of magnitude, and the Euclidean fronts are
  consistently among the smallest, which biases $Delta R_2$ *toward* the curved arms.

  $tilde(kappa)$ is the median $|K| dot R_"g"^2$ of @eq:kappa over the front --- what
  the optimiser actually chose.  It shares its gauge with the $kappa$ the detector infers
  in @tab:wilson-fit, so the two columns may be set side by side.  Both are $0$ for the
  Euclidean arm, where $K = 0$ exactly.
  ],
) <tab:geometry-match-r2>
