// Generated by scripts/exp1_wilson_typst.py -- do not edit by hand.
#figure(
  table(
    columns: 4,
    align: (left, left, right, right),
    stroke: none,
    inset: (x: 2.5pt, y: 4pt),
    table.hline(stroke: 0.8pt),
    table.header(
      [*Dataset*], [*Geom.*], [$rho$], [$kappa$],
    ),
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[grid\ #text(size: 0.8em)[(euclidean)]], [sph], [$0.116$#super[†]], [$5.81$#super[†]],
    [*euc*], [$0.127$], [$0$],
    [hyp], [$0.130$#super[†]], [$0.0100$#super[†]],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[sphere\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.0851$], [$2.99$],
    [euc], [$0.277$], [$0$],
    [hyp], [$0.284$#super[†]], [$0.0100$#super[†]],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[antipodal\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.0219$], [$4.22$],
    [euc], [$0.142$], [$0$],
    [hyp], [$0.144$#super[†]], [$0.0100$#super[†]],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[tree\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.0625$], [$5.73$],
    [euc], [$0.0673$], [$0$],
    [*hyp*], [$0.0675$#super[†]], [$0.0100$#super[†]],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[hyp. shells\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.0632$], [$7.77$],
    [euc], [$0.0701$], [$0$],
    [*hyp*], [$0.0711$#super[†]], [$0.0100$#super[†]],
    table.hline(stroke: 0.8pt),
  ),
  caption: [The constant-curvature fit of each synthetic dataset of known intrinsic
  geometry ($N = 1000$), scored as an embedding.
  Each dataset is fitted under all three geometries; the row whose geometry matches
  the data's intrinsic curvature sign is set in bold.

  Each arm of @tab:geometry-inference fits a constant-curvature Gram matrix $Z(r)$ to
  the data; because that $Z$ *is* the Gram matrix of the model it tests for, its
  retained eigen-block is an embedding.  Reconstructing it and scoring it with the
  same metric code every t-SNE trial goes through puts the fit at a single point of the
  ten-objective space, so what the detector infers is stated in the same units as what
  the sweep achieved in @tab:geometry-match-r2.
  $rho$ is that arm's normalised signature residual, gauged by $n dot d_"max"^2$;
  it is also exactly the eigenvalue mass the reconstruction discarded, so it is the
  reconstruction's own error and not a separate misfit score.

  $kappa = |K| dot R_"rms"^2$ of @eq:kappa, measured on the configuration the
  fit implies.  It shares that gauge with $tilde(kappa)$ of @tab:geometry-match-r2, so
  the two may be set side by side --- what the detector infers about the data against
  what the optimiser actually chose.  It is $0$ for the Euclidean arm, where $K = 0$
  exactly.

  A dagger marks a fit pinned on the flat-ward edge of its search window, where the
  reported value is the bound and not a measurement.  The hyperbolic search is capped
  at the radius where $kappa$ falls to $0.01$, so a pinned hyperbolic arm reports
  exactly that --- the cap is a bound on the same $kappa$ the column shows.  Every
  hyperbolic arm here is pinned, so no hyperbolic reconstruction in this table is
  meaningfully curved: the column tests the Euclidean null rather than a hyperbolic
  alternative, which is why its $rho$ tracks the Euclidean arm's so closely.
  ],
) <tab:wilson-fit>
