// Generated by scripts/exp1_r2_typst.py -- do not edit by hand.
#figure(
  table(
    columns: 6,
    align: (left, left, right, right, right, right),
    stroke: none,
    inset: (x: 2.5pt, y: 4pt),
    table.hline(stroke: 0.8pt),
    table.header(
      [*Dataset*], [*Geom.*], [$R_2$], [$Delta R_2$], [$tilde(kappa)$], [$n_"front"$],
    ),
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[grid\ #text(size: 0.8em)[(euclidean)]], [sph], [$8.73 dot 10^(-3)$], [$+0.0012$], [$2.57$], [$147$],
    [*euc*], [$9.90 dot 10^(-3)$], [---], [$0$], [$163$],
    [hyp], [$9.50 dot 10^(-3)$], [$+0.0004$], [$0.0232$], [$179$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[sphere\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.149$], [$+0.0126$], [$2.94$], [$361$],
    [euc], [$0.161$], [---], [$0$], [$176$],
    [hyp], [$0.157$], [$+0.0044$], [$3.41 dot 10^(-3)$], [$309$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[antipodal\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.0459$], [$+0.0043$], [$2.47$], [$239$],
    [euc], [$0.0502$], [---], [$0$], [$225$],
    [hyp], [$0.0470$], [$+0.0032$], [$0.0437$], [$258$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[tree\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.0546$], [$+0.0083$], [$2.47$], [$380$],
    [euc], [$0.0629$], [---], [$0$], [$244$],
    [*hyp*], [$0.0458$], [$+0.0172$], [$1.54$], [$387$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[hyp. shells\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.125$], [$+0.0195$], [$2.47$], [$604$],
    [euc], [$0.144$], [---], [$0$], [$456$],
    [*hyp*], [$0.123$], [$+0.0206$], [$4.43 dot 10^(-5)$], [$554$],
    table.hline(stroke: 0.8pt),
  ),
  caption: [Experiment 1: matched embedding geometry against the Euclidean baseline,
  on the synthetic datasets of known intrinsic geometry ($N = 5000$, `all_off`,
  preference region $W_"all"$).
  Each dataset is embedded under all three geometries; the row whose geometry matches
  the data's intrinsic curvature sign is set in bold.

  $R_2$ is the R2 indicator of the cell's Pareto front (@eq:r2), a *cost*: smaller is
  better.  $Delta R_2 = R_2("euc") - R_2("geom")$ is therefore formed baseline-minus-row,
  so a positive value means the row's geometry improved on the Euclidean baseline ---
  the same reading direction as @eq:r2-gain.
  $n_"front"$ is the front's size, reported because $R_2$ improves monotonically
  with it: fronts here range over an order of magnitude, and the Euclidean fronts are
  consistently among the smallest, which biases $Delta R_2$ *toward* the curved arms.

  $tilde(kappa)$ is the median $|K| dot R_"rms"^2$ of @eq:kappa over the front --- what
  the optimiser actually chose.  It shares its gauge with the $kappa$ the detector infers
  in @tab:wilson-fit, so the two columns may be set side by side.  Both are $0$ for the
  Euclidean arm, where $K = 0$ exactly.
  ],
) <tab:geometry-match-r2>
