// Generated by scripts/exp1_typst.py -- do not edit by hand.
#figure(
  table(
    columns: 11,
    align: (left, left, right, right, right, right, right, right, center, right, right),
    stroke: none,
    inset: (x: 2.5pt, y: 4pt),
    table.hline(stroke: 0.8pt),
    table.header(
      table.cell(rowspan: 2)[*Dataset*], table.cell(rowspan: 2)[*Geom.*], table.cell(colspan: 2)[*Wilson fit*], table.cell(colspan: 4)[*Pareto front*], table.cell(colspan: 3)[*Wilson point vs. front*],
      [$rho$], [$kappa$], [$R_2$], [$Delta R_2$], [$tilde(kappa)$], [$n_"front"$], [dom.], [$I_epsilon (F, w)$], [$I_epsilon (w, F)$],
    ),
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[grid\ #text(size: 0.8em)[(euclidean)]], [sph], [$0.116$#super[†]], [$5.81$#super[†]], [$0.0174$], [$+0.0020$], [$2.50$], [$166$], [yes], [$-0.1818$], [$+0.5750$],
    [*euc*], [$0.127$], [$0$], [$0.0194$], [---], [$0$], [$344$], [yes], [$-0.1895$], [$+0.5828$],
    [hyp], [$0.130$#super[†]], [$0.0100$#super[†]], [$0.0170$], [$+0.0023$], [$0.135$], [$126$], [yes], [$-0.1898$], [$+0.5851$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[sphere\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.0851$], [$2.99$], [$0.150$], [$+0.0124$], [$2.47$], [$289$], [no], [$+0.0485$], [$+0.1462$],
    [euc], [$0.277$], [$0$], [$0.163$], [---], [$0$], [$255$], [yes], [$-0.0057$], [$+0.2136$],
    [hyp], [$0.284$#super[†]], [$0.0100$#super[†]], [$0.155$], [$+0.0076$], [$0.578$], [$357$], [no], [$+0.0002$], [$+0.2140$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[antipodal\ #text(size: 0.8em)[(spherical)]], [*sph*], [$0.0219$], [$4.22$], [$0.0502$], [$+0.0037$], [$2.47$], [$226$], [no], [$+0.0254$], [$+0.0639$],
    [euc], [$0.142$], [$0$], [$0.0539$], [---], [$0$], [$46$], [no], [$+0.0426$], [$+0.0947$],
    [hyp], [$0.144$#super[†]], [$0.0100$#super[†]], [$0.0519$], [$+0.0020$], [$0.202$], [$127$], [no], [$+0.0450$], [$+0.1004$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[tree\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.0625$], [$5.73$], [$0.0786$], [$+0.0023$], [$2.47$], [$203$], [no], [$+0.1601$], [$+0.0292$],
    [euc], [$0.0673$], [$0$], [$0.0809$], [---], [$0$], [$146$], [no], [$+0.0703$], [$+0.0035$],
    [*hyp*], [$0.0675$#super[†]], [$0.0100$#super[†]], [$0.0577$], [$+0.0232$], [$13.1$], [$524$], [no], [$+0.0633$], [$+0.2018$],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 3)[hyp. shells\ #text(size: 0.8em)[(hyperbolic)]], [sph], [$0.0632$], [$7.77$], [$0.135$], [$+0.0333$], [$2.47$], [$365$], [no], [$+0.2966$], [$+0.2655$],
    [euc], [$0.0701$], [$0$], [$0.168$], [---], [$0$], [$241$], [no], [$+0.1586$], [$+0.2323$],
    [*hyp*], [$0.0711$#super[†]], [$0.0100$#super[†]], [$0.127$], [$+0.0406$], [$3.95 dot 10^(-6)$], [$580$], [no], [$+0.1352$], [$+0.2714$],
    table.hline(stroke: 0.8pt),
  ),
  caption: [Experiment 1: matched embedding geometry against the Euclidean baseline,
  on the synthetic datasets of known intrinsic geometry ($N = 1000$, `all_off`,
  preference region $W_"all"$).
  Each dataset is embedded under all three geometries; the row whose geometry matches
  the data's intrinsic curvature sign is set in bold.

  $R_2$ is the R2 indicator of the cell's Pareto front (@eq:r2), a *cost*: smaller is
  better.  $Delta R_2 = R_2("euc") - R_2("geom")$ is therefore formed baseline-minus-row,
  so a positive value means the row's geometry improved on the Euclidean baseline ---
  the same reading direction as @eq:r2-gain.
  $n_"front"$ is the front's size, reported because $R_2$ improves monotonically
  with it: fronts here range over an order of magnitude, and the Euclidean fronts are
  consistently among the smallest, which biases $Delta R_2$ *toward* the curved arms.
  It also guards the $epsilon$ columns, which carry the opposite bias: being blind
  to cardinality is the price of carrying no parameters, so a 46-point front can
  score as a 580-point one.

  Both $kappa$ columns are the same quantity, $|K| dot R_"rms"^2$ of @eq:kappa: the
  Wilson arm's is measured on the configuration its fit implies, $tilde(kappa)$ is the
  median over the front.  They share a gauge, so the pair reads as a comparison ---
  what the detector infers about the data against what the optimiser actually chose.
  Both are $0$ for the Euclidean arm, where $K = 0$ exactly.

  The Wilson columns bring the curvature detector into the same objective space.
  Each arm of @tab:geometry-inference fits a constant-curvature Gram matrix $Z(r)$ to
  the data; because that $Z$ *is* the Gram matrix of the model it tests for, its
  retained eigen-block is an embedding.  Reconstructing it and scoring it with the
  same metric code every t-SNE trial goes through puts the fit at a single point $w$ of
  the ten-objective space, so it can be compared with the front rather than merely set
  beside it.
  $rho$ is that arm's normalised signature residual, gauged by $n dot d_"max"^2$;
  it is also exactly the eigenvalue mass the reconstruction discarded, so it is the
  reconstruction's own error and not a separate misfit score.

  The last three columns place $w$ against the front $F$ without any preference
  model at all.  `dom.` says whether some front point dominates $w$ outright: `no`
  means a single eigendecomposition reached a part of objective space that a
  thousand qParEGO trials did not.
  $I_epsilon (A, B)$ is the binary additive $epsilon$-indicator, the smallest shift
  that makes $A$ cover $B$; $I_epsilon (A, B) <= 0$ iff $A$ covers $B$ outright.
  It is asymmetric and both directions are reported, since neither settles anything
  alone when the two cross: $I_epsilon (F, w)$ is how far the front falls short of
  covering the Wilson point --- its sign is the `dom.` verdict and its magnitude the
  margin --- while $I_epsilon (w, F)$ is how far that one point falls short of
  covering the whole front.

  A dagger marks a fit pinned on the flat-ward edge of its search window, where the
  reported value is the bound and not a measurement.  The hyperbolic search is capped
  at the radius where $kappa$ falls to $0.01$, so a pinned hyperbolic arm reports
  exactly that --- the cap is a bound on the same $kappa$ the column shows.  Every
  hyperbolic arm here is pinned, so no hyperbolic reconstruction in this table is
  meaningfully curved: the column tests the Euclidean null rather than a hyperbolic
  alternative, which is why its $rho$ tracks the Euclidean arm's so closely.
  ],
) <tab:geometry-match>
