// Generated by scripts/r2_delta_typst.py -- do not edit by hand.
#[
  #show figure: set block(breakable: true)
  #figure(
    table(
      columns: 11,
      align: (left, left, left, right, right, right, right, right, right, right, right),
      stroke: none,
      inset: (x: 2.5pt, y: 3pt),
      table.hline(stroke: 0.8pt),
      table.header(
        table.cell(rowspan: 2, align: horizon)[*Dataset*], table.cell(rowspan: 2, align: horizon)[*Geom.*], table.cell(rowspan: 2, align: horizon)[*Setting*], table.cell(rowspan: 2, align: horizon + right)[$W_"all"$], table.cell(colspan: 5, align: center)[*Per-metric*], table.cell(colspan: 2, align: center)[*Surface*],
        [$W_"trust"$], [$W_"cont"$], [$W_"stress"$], [$W_"shep"$], [$W_"nh"$], [$W_"man"$], [$W_"proj"$],
      ),
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[grid], table.cell(rowspan: 4)[sph], [`all_off`], [$8.73$], [$4.34$], [$4.30$], [$17.4$], [$5.39$], [$14.4$], [$11.5$], [$7.89$],
      [`centering_only`], [$bold(+0.09)$], [$bold(+0.13)$], [$+0.11$], [$bold(+0.76)$], [$bold(+0.01)$], [$-0.21$], [$-0.07$], [$bold(+0.86)$],
      [`global_only`], [$+0.04$], [$+0.09$], [$bold(+0.14)$], [$-0.46$], [$-0.07$], [$bold(+1.24)$], [$bold(+0.28)$], [$-0.06$],
      [`all_free`], [$+0.05$], [$+0.06$], [$+0.12$], [$+0.15$], [$-0.02$], [$+0.27$], [$-0.14$], [$+0.47$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[grid]], table.cell(rowspan: 5)[euc], [`all_off`], [$9.90$], [$5.14$], [$5.14$], [$20.8$], [$5.94$], [$15.5$], [$11.7$], [$11.7$],
      [`centering_only`], [$-0.01$], [$-0.01$], [$-0.01$], [$-0.03$], [$-0.01$], [$approx 0$], [$-0.01$], [$-0.01$],
      [`global_only`], [$-0.06$], [$-0.06$], [$+0.09$], [$-0.59$], [$-0.14$], [$+0.93$], [$+0.01$], [$+0.01$],
      [`norm_only`], [$bold(+0.19)$], [$bold(+0.20)$], [$bold(+0.26)$], [$-0.09$], [$-0.02$], [$bold(+1.32)$], [$bold(+0.31)$], [$bold(+0.31)$],
      [`all_free`], [$+0.14$], [$+0.13$], [$+0.23$], [$-0.16$], [$-0.05$], [$+1.22$], [$+0.25$], [$+0.25$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[grid]], table.cell(rowspan: 5)[hyp], [`all_off`], [$9.50$], [$4.91$], [$4.68$], [$21.2$], [$6.00$], [$11.9$], [$10.9$], [$11.1$],
      [`centering_only`], [$bold(+0.88)$], [$bold(+0.45)$], [$bold(+0.45)$], [$bold(+3.77)$], [$bold(+0.70)$], [$-0.02$], [$bold(+0.98)$], [$bold(+2.58)$],
      [`global_only`], [$-0.03$], [$-0.05$], [$-0.05$], [$approx 0$], [$-0.02$], [$-0.11$], [$-0.06$], [$-0.05$],
      [`norm_only`], [$+0.11$], [$+0.14$], [$+0.02$], [$+0.16$], [$+0.06$], [$bold(+0.15)$], [$+0.11$], [$+0.15$],
      [`all_free`], [$+0.48$], [$+0.29$], [$+0.24$], [$+2.65$], [$+0.53$], [$-0.57$], [$+0.27$], [$+2.52$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[sphere], table.cell(rowspan: 4)[sph], [`all_off`], [$149$], [$101$], [$101$], [$174$], [$299$], [$149$], [$165$], [$198$],
      [`centering_only`], [$bold(+1.55)$], [$-0.82$], [$bold(+0.77)$], [$+0.82$], [$bold(+2.90)$], [$bold(+1.56)$], [$bold(+1.82)$], [$bold(+1.33)$],
      [`global_only`], [$-3.04$], [$-1.21$], [$-1.43$], [$+1.31$], [$-3.38$], [$-14.7$], [$-0.95$], [$-6.13$],
      [`all_free`], [$+0.78$], [$-1.25$], [$+0.25$], [$bold(+3.56)$], [$+1.93$], [$-3.14$], [$+1.40$], [$+0.41$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[sphere]], table.cell(rowspan: 5)[euc], [`all_off`], [$161$], [$105$], [$110$], [$211$], [$328$], [$149$], [$197$], [$197$],
      [`centering_only`], [$-3.63$], [$-0.75$], [$-1.05$], [$-0.02$], [$-0.03$], [$-24.5$], [$-5.25$], [$-5.25$],
      [`global_only`], [$-2.07$], [$-2.95$], [$-0.49$], [$-0.87$], [$-2.46$], [$-8.28$], [$-3.09$], [$-3.09$],
      [`norm_only`], [$bold(+2.94)$], [$bold(+0.52)$], [$bold(+0.84)$], [$bold(+0.28)$], [$bold(+2.58)$], [$bold(+15.6)$], [$bold(+3.98)$], [$bold(+3.98)$],
      [`all_free`], [$+1.49$], [$-0.26$], [$+0.21$], [$-0.19$], [$-0.61$], [$+12.5$], [$+2.18$], [$+2.18$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[sphere]], table.cell(rowspan: 5)[hyp], [`all_off`], [$157$], [$103$], [$109$], [$172$], [$326$], [$157$], [$184$], [$198$],
      [`centering_only`], [$+0.80$], [$+5.04$], [$+0.57$], [$bold(+2.62)$], [$+0.54$], [$-7.56$], [$+2.15$], [$-0.56$],
      [`global_only`], [$bold(+2.95)$], [$bold(+6.18)$], [$+1.05$], [$+1.37$], [$bold(+1.00)$], [$+6.94$], [$bold(+5.15)$], [$bold(+2.51)$],
      [`norm_only`], [$+2.29$], [$-1.27$], [$+0.44$], [$-0.78$], [$+0.10$], [$+10.7$], [$+3.31$], [$+0.82$],
      [`all_free`], [$+2.65$], [$-5.16$], [$bold(+1.27)$], [$+0.67$], [$+0.32$], [$bold(+13.4)$], [$+3.60$], [$+0.73$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[antipodal], table.cell(rowspan: 4)[sph], [`all_off`], [$45.9$], [$52.6$], [$43.4$], [$71.3$], [$58.1$], [$26.4$], [$51.0$], [$59.9$],
      [`centering_only`], [$bold(+0.46)$], [$bold(+0.08)$], [$+0.12$], [$bold(+0.91)$], [$bold(+1.56)$], [$bold(+0.30)$], [$bold(+0.40)$], [$bold(+0.84)$],
      [`global_only`], [$-0.81$], [$-0.40$], [$-1.30$], [$+0.86$], [$-0.99$], [$-0.28$], [$-1.17$], [$-0.06$],
      [`all_free`], [$-0.46$], [$-2.55$], [$bold(+0.18)$], [$+0.26$], [$-1.52$], [$-0.35$], [$-0.28$], [$-1.16$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[antipodal]], table.cell(rowspan: 5)[euc], [`all_off`], [$50.2$], [$53.2$], [$43.9$], [$89.1$], [$65.3$], [$28.9$], [$61.2$], [$61.2$],
      [`centering_only`], [$bold(+0.01)$], [$+0.47$], [$-0.17$], [$-0.32$], [$-0.01$], [$approx 0$], [$-0.04$], [$-0.04$],
      [`global_only`], [$-0.18$], [$bold(+0.85)$], [$bold(+0.08)$], [$-0.43$], [$-1.10$], [$-0.05$], [$-0.19$], [$-0.19$],
      [`norm_only`], [$-0.25$], [$-0.03$], [$-0.72$], [$bold(+0.10)$], [$approx 0$], [$-0.03$], [$-0.18$], [$-0.18$],
      [`all_free`], [$-0.34$], [$+0.76$], [$-0.03$], [$-1.42$], [$-0.78$], [$-0.18$], [$-0.38$], [$-0.38$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[antipodal]], table.cell(rowspan: 5)[hyp], [`all_off`], [$47.0$], [$50.2$], [$44.1$], [$71.2$], [$66.0$], [$27.3$], [$53.0$], [$60.9$],
      [`centering_only`], [$bold(+0.52)$], [$-1.66$], [$bold(+0.35)$], [$+0.11$], [$bold(+4.37)$], [$bold(+0.25)$], [$bold(+0.36)$], [$bold(+1.26)$],
      [`global_only`], [$-0.25$], [$-0.01$], [$-0.60$], [$-0.42$], [$+0.51$], [$+0.08$], [$-0.40$], [$+0.26$],
      [`norm_only`], [$-0.85$], [$-3.49$], [$-0.17$], [$bold(+0.63)$], [$-1.13$], [$-0.36$], [$-1.10$], [$-0.79$],
      [`all_free`], [$-0.54$], [$-4.94$], [$-0.27$], [$+0.31$], [$+2.59$], [$-0.04$], [$-0.57$], [$-0.41$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[tree], table.cell(rowspan: 4)[sph], [`all_off`], [$54.6$], [$29.8$], [$33.0$], [$143$], [$45.5$], [$28.6$], [$54.2$], [$72.0$],
      [`centering_only`], [$+0.01$], [$+0.05$], [$bold(+0.01)$], [$approx 0$], [$-0.02$], [$approx 0$], [$+0.01$], [$+0.01$],
      [`global_only`], [$-2.51$], [$-1.30$], [$-1.14$], [$-5.29$], [$-4.81$], [$-1.32$], [$-4.10$], [$-1.88$],
      [`all_free`], [$bold(+0.05)$], [$bold(+0.09)$], [$-0.01$], [$bold(+0.22)$], [$-0.06$], [$-0.01$], [$bold(+0.07)$], [$bold(+0.01)$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[tree]], table.cell(rowspan: 5)[euc], [`all_off`], [$62.9$], [$33.3$], [$36.5$], [$169$], [$50.1$], [$32.2$], [$72.8$], [$72.8$],
      [`centering_only`], [$approx 0$], [$+0.01$], [$-0.01$], [$approx 0$], [$approx 0$], [$approx 0$], [$approx 0$], [$approx 0$],
      [`global_only`], [$-0.15$], [$-0.07$], [$-0.09$], [$-0.07$], [$-0.53$], [$-0.11$], [$-0.18$], [$-0.18$],
      [`norm_only`], [$bold(+0.55)$], [$bold(+0.18)$], [$bold(+0.21)$], [$bold(+2.22)$], [$-0.37$], [$bold(+0.20)$], [$bold(+0.59)$], [$bold(+0.59)$],
      [`all_free`], [$+0.40$], [$+0.12$], [$+0.04$], [$+2.21$], [$-0.93$], [$+0.07$], [$+0.40$], [$+0.40$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[tree]], table.cell(rowspan: 5)[hyp], [`all_off`], [$45.8$], [$24.4$], [$26.4$], [$118$], [$43.2$], [$23.3$], [$28.9$], [$72.6$],
      [`centering_only`], [$+0.07$], [$-0.21$], [$-0.14$], [$-0.12$], [$+0.92$], [$-0.02$], [$-0.62$], [$+0.85$],
      [`global_only`], [$-0.19$], [$-0.14$], [$-0.18$], [$-0.16$], [$-0.25$], [$-0.16$], [$-0.34$], [$-0.03$],
      [`norm_only`], [$+0.32$], [$+0.21$], [$+0.14$], [$bold(+1.53)$], [$-0.65$], [$+0.25$], [$+0.48$], [$+0.38$],
      [`all_free`], [$bold(+2.23)$], [$bold(+1.32)$], [$bold(+0.37)$], [$+1.03$], [$bold(+9.40)$], [$bold(+1.83)$], [$bold(+1.74)$], [$bold(+3.43)$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[hyp. shells], table.cell(rowspan: 4)[sph], [`all_off`], [$125$], [$111$], [$97.9$], [$220$], [$173$], [$90.1$], [$146$], [$159$],
      [`centering_only`], [$bold(+3.66)$], [$-1.00$], [$bold(+1.10)$], [$bold(+6.77)$], [$bold(+14.3)$], [$bold(+0.98)$], [$bold(+8.70)$], [$bold(+0.27)$],
      [`global_only`], [$-12.8$], [$-3.90$], [$-12.5$], [$-16.8$], [$-0.25$], [$-15.1$], [$-9.30$], [$-18.3$],
      [`all_free`], [$-6.59$], [$-0.68$], [$-4.70$], [$-5.05$], [$+6.05$], [$-10.2$], [$-1.99$], [$-10.8$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[hyp. shells]], table.cell(rowspan: 5)[euc], [`all_off`], [$144$], [$135$], [$103$], [$231$], [$190$], [$114$], [$171$], [$171$],
      [`centering_only`], [$+11.6$], [$-3.14$], [$+3.76$], [$+2.55$], [$+13.4$], [$+21.1$], [$+10.7$], [$+10.7$],
      [`global_only`], [$+11.9$], [$-1.40$], [$+3.62$], [$+1.96$], [$+13.4$], [$+23.9$], [$+11.7$], [$+11.7$],
      [`norm_only`], [$bold(+32.8)$], [$-0.78$], [$bold(+14.4)$], [$+54.7$], [$bold(+52.6)$], [$bold(+41.1)$], [$bold(+37.1)$], [$bold(+37.1)$],
      [`all_free`], [$+32.2$], [$-2.46$], [$+13.4$], [$bold(+54.7)$], [$+51.4$], [$+41.0$], [$+36.4$], [$+36.4$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[hyp. shells]], table.cell(rowspan: 5)[hyp], [`all_off`], [$123$], [$112$], [$97.4$], [$216$], [$170$], [$90.1$], [$143$], [$160$],
      [`centering_only`], [$-28.3$], [$-4.61$], [$-16.5$], [$-21.5$], [$-4.47$], [$-108$], [$-45.8$], [$-23.6$],
      [`global_only`], [$-13.8$], [$-3.85$], [$-15.0$], [$-18.5$], [$-0.62$], [$-15.6$], [$-8.96$], [$-21.3$],
      [`norm_only`], [$+19.8$], [$-0.27$], [$bold(+13.6)$], [$bold(+55.4)$], [$+33.3$], [$+20.6$], [$bold(+40.4)$], [$+15.6$],
      [`all_free`], [$bold(+25.4)$], [$-4.18$], [$+12.0$], [$+52.4$], [$bold(+75.0)$], [$bold(+23.8)$], [$+32.2$], [$bold(+34.2)$],
      table.hline(stroke: 0.8pt),
    ),
    caption: [Experiment 2: R2 indicator gain $Delta R_2$ of each loss-weight setting over the
    `all_off` baseline on the synthetic datasets of known intrinsic geometry, under each preference region of @preference-regions
    ($N = 5000$).

    Every entry is multiplied by $1000$, so a table entry of $1$ is an indicator value
    of $10^(-3)$.
    The `all_off` row opening each geometry block is the baseline *level* $R_2$ of that front
    (@eq:r2), a cost: smaller is better.  Every row below it is the *gain*
    $Delta R_2 = R_2("all_off") - R_2("setting")$ of @eq:r2-gain, formed
    baseline-minus-setting so that a positive value means the setting improved on the
    baseline.  Levels are therefore unsigned and gains always carry a sign.
    Within each geometry block the largest positive gain per region is set in bold; a block
    with no positive gain has no bold entry.  An entry of $approx 0$ is a gain below the
    resolution printed here, where the front barely moved and the sign carries nothing.

    The columns are the weight sets of @preference-regions: $W_"all"$ is the full simplex and
    is the only one under which $Delta R_2$ is a claim about overall front quality; the five
    per-metric regions hold the weight vectors placing at least half their mass on that
    metric's two objectives; $W_"man"$ and $W_"proj"$ hold those supported entirely on the
    five manifold, respectively the five projected, objectives.  A setting that helps under
    one priority and costs under another is visible as a sign change along its row.

    `norm_only` is absent from every spherical block because the depth-norm loss is
    undefined on the sphere (@norm-loss).  `rms_anchored` is not an ablation of a loss term
    and is reported with the curvature results (@curvature-magnitude-results) instead.
  ],
  ) <tab:r2-delta-synthetic-n5000>
]
