// Generated by scripts/r2_delta_typst.py -- do not edit by hand.
#[
  #show figure: set block(breakable: true)
  #figure(
    table(
      columns: 11,
      align: (left, left, left, right, right, right, right, right, right, right, right),
      stroke: none,
      inset: (x: 2.5pt, y: 3pt),
      table.hline(stroke: 0.8pt),
      table.header(
        table.cell(rowspan: 2, align: horizon)[*Dataset*], table.cell(rowspan: 2, align: horizon)[*Geom.*], table.cell(rowspan: 2, align: horizon)[*Setting*], table.cell(rowspan: 2, align: horizon + right)[$W_"all"$], table.cell(colspan: 5, align: center)[*Per-metric*], table.cell(colspan: 2, align: center)[*Surface*],
        [$W_"trust"$], [$W_"cont"$], [$W_"stress"$], [$W_"shep"$], [$W_"nh"$], [$W_"man"$], [$W_"proj"$],
      ),
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[MNIST], table.cell(rowspan: 4)[sph], [`all_off`], [$129$], [$79.2$], [$78.5$], [$171$], [$238$], [$148$], [$154$], [$162$],
      [`centering_only`], [$bold(+5.00)$], [$bold(+2.57)$], [$bold(+2.86)$], [$bold(+9.23)$], [$+10.4$], [$+2.68$], [$bold(+9.38)$], [$+3.18$],
      [`global_only`], [$+3.87$], [$+2.06$], [$+2.24$], [$+2.68$], [$bold(+11.2)$], [$+3.02$], [$+3.99$], [$bold(+4.80)$],
      [`all_free`], [$+3.87$], [$+1.55$], [$+1.90$], [$+8.05$], [$+8.39$], [$bold(+3.48)$], [$+7.99$], [$+1.98$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[MNIST]], table.cell(rowspan: 5)[euc], [`all_off`], [$129$], [$78.2$], [$77.5$], [$202$], [$221$], [$142$], [$157$], [$157$],
      [`centering_only`], [$-2.10$], [$-0.69$], [$-1.03$], [$-1.09$], [$-5.00$], [$-3.99$], [$-2.81$], [$-2.23$],
      [`global_only`], [$-9.26$], [$-4.50$], [$-5.41$], [$-2.31$], [$-32.2$], [$-7.11$], [$-11.2$], [$-11.3$],
      [`norm_only`], [$bold(+11.6)$], [$bold(+4.79)$], [$bold(+6.09)$], [$bold(+0.68)$], [$bold(+63.5)$], [$-15.4$], [$bold(+13.3)$], [$bold(+13.2)$],
      [`all_free`], [$+6.23$], [$+1.19$], [$+3.23$], [$-0.13$], [$+40.1$], [$-19.5$], [$+6.19$], [$+6.08$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[MNIST]], table.cell(rowspan: 5)[hyp], [`all_off`], [$120$], [$73.7$], [$73.4$], [$154$], [$229$], [$137$], [$133$], [$157$],
      [`centering_only`], [$bold(+4.68)$], [$bold(+3.93)$], [$bold(+2.93)$], [$bold(+2.07)$], [$bold(+12.1)$], [$bold(+3.55)$], [$bold(+5.81)$], [$bold(+4.82)$],
      [`global_only`], [$-0.81$], [$+0.50$], [$-0.50$], [$+0.16$], [$-4.15$], [$-1.72$], [$-1.14$], [$-1.38$],
      [`norm_only`], [$-1.33$], [$-0.11$], [$-0.82$], [$+1.46$], [$-2.62$], [$-5.63$], [$-1.47$], [$-2.27$],
      [`all_free`], [$-1.84$], [$-0.78$], [$-1.34$], [$+0.44$], [$-5.27$], [$-1.11$], [$-2.98$], [$-0.46$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[F-MNIST], table.cell(rowspan: 4)[sph], [`all_off`], [$101$], [$58.5$], [$58.2$], [$147$], [$98.5$], [$198$], [$122$], [$123$],
      [`centering_only`], [$+0.21$], [$-0.01$], [$+0.27$], [$-2.27$], [$+3.01$], [$+1.60$], [$-0.91$], [$+1.90$],
      [`global_only`], [$+0.05$], [$-0.04$], [$+0.05$], [$-0.05$], [$-0.36$], [$+1.60$], [$+0.17$], [$+0.23$],
      [`all_free`], [$bold(+0.90)$], [$bold(+0.46)$], [$bold(+0.64)$], [$bold(+0.01)$], [$bold(+3.53)$], [$bold(+2.64)$], [$bold(+0.54)$], [$bold(+2.41)$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[F-MNIST]], table.cell(rowspan: 5)[euc], [`all_off`], [$102$], [$58.7$], [$58.4$], [$150$], [$99.4$], [$197$], [$123$], [$123$],
      [`centering_only`], [$+0.07$], [$+0.01$], [$+0.03$], [$+0.08$], [$-0.04$], [$+0.33$], [$+0.08$], [$+0.08$],
      [`global_only`], [$+0.45$], [$+0.26$], [$+0.26$], [$+0.12$], [$-0.25$], [$+2.47$], [$+0.59$], [$+0.59$],
      [`norm_only`], [$bold(+3.93)$], [$bold(+2.69)$], [$bold(+2.88)$], [$bold(+2.38)$], [$bold(+21.3)$], [$+0.50$], [$bold(+5.81)$], [$bold(+5.81)$],
      [`all_free`], [$+2.47$], [$+1.77$], [$+1.66$], [$+0.07$], [$+12.3$], [$bold(+2.94)$], [$+3.63$], [$+3.63$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[F-MNIST]], table.cell(rowspan: 5)[hyp], [`all_off`], [$95.4$], [$55.4$], [$54.9$], [$123$], [$95.2$], [$196$], [$107$], [$122$],
      [`centering_only`], [$bold(+0.36)$], [$bold(+0.02)$], [$bold(+0.22)$], [$bold(+1.23)$], [$bold(+1.42)$], [$+0.44$], [$bold(+0.39)$], [$bold(+1.19)$],
      [`global_only`], [$-0.23$], [$-0.14$], [$-0.18$], [$-0.37$], [$-3.04$], [$+2.15$], [$-0.75$], [$+0.18$],
      [`norm_only`], [$-0.35$], [$-0.19$], [$-0.27$], [$+0.74$], [$-3.33$], [$+1.02$], [$-0.79$], [$+0.09$],
      [`all_free`], [$-0.26$], [$-0.16$], [$-0.16$], [$-0.35$], [$-3.47$], [$bold(+2.50)$], [$-1.39$], [$+0.35$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[PBMC], table.cell(rowspan: 4)[sph], [`all_off`], [$106$], [$74.5$], [$67.0$], [$219$], [$157$], [$60.8$], [$128$], [$127$],
      [`centering_only`], [$-0.26$], [$-0.01$], [$+0.10$], [$-0.20$], [$-1.01$], [$-0.12$], [$+0.21$], [$-0.75$],
      [`global_only`], [$bold(+0.42)$], [$bold(+0.20)$], [$bold(+0.27)$], [$bold(+0.32)$], [$bold(+1.36)$], [$bold(+0.22)$], [$bold(+1.52)$], [$-0.55$],
      [`all_free`], [$-0.23$], [$-0.07$], [$+0.11$], [$-1.38$], [$+0.59$], [$-0.11$], [$+0.12$], [$-0.60$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[PBMC]], table.cell(rowspan: 5)[euc], [`all_off`], [$106$], [$74.2$], [$66.6$], [$219$], [$156$], [$60.5$], [$127$], [$127$],
      [`centering_only`], [$-0.61$], [$-0.35$], [$-0.26$], [$+0.21$], [$-2.85$], [$-0.38$], [$-0.76$], [$-0.76$],
      [`global_only`], [$-0.85$], [$-0.74$], [$-0.54$], [$-0.86$], [$-2.30$], [$-0.53$], [$-1.07$], [$-1.07$],
      [`norm_only`], [$bold(+33.3)$], [$+8.25$], [$+13.6$], [$bold(+47.6)$], [$+100$], [$bold(+18.9)$], [$bold(+40.9)$], [$bold(+40.9)$],
      [`all_free`], [$+33.2$], [$bold(+8.35)$], [$bold(+14.2)$], [$+46.1$], [$bold(+102)$], [$+18.6$], [$+40.8$], [$+40.8$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[PBMC]], table.cell(rowspan: 5)[hyp], [`all_off`], [$95.5$], [$69.6$], [$60.8$], [$187$], [$147$], [$54.8$], [$98.1$], [$127$],
      [`centering_only`], [$bold(+3.39)$], [$bold(+1.03)$], [$bold(+1.48)$], [$bold(+1.15)$], [$bold(+11.3)$], [$bold(+1.73)$], [$+0.55$], [$bold(+6.12)$],
      [`global_only`], [$-0.48$], [$+1.01$], [$-0.12$], [$-2.45$], [$+0.18$], [$-0.28$], [$-0.23$], [$-0.65$],
      [`norm_only`], [$+0.39$], [$+0.74$], [$+0.38$], [$-1.39$], [$+3.21$], [$+0.10$], [$bold(+1.11)$], [$-0.08$],
      [`all_free`], [$+1.35$], [$+0.17$], [$+0.39$], [$-2.49$], [$+6.58$], [$+0.47$], [$-4.82$], [$+6.11$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[WordNet], table.cell(rowspan: 4)[sph], [`all_off`], [$100$], [$54.9$], [$57.9$], [$179$], [$180$], [$65.2$], [$119$], [$119$],
      [`centering_only`], [$bold(+0.69)$], [$bold(+0.44)$], [$bold(+0.58)$], [$+1.19$], [$bold(+0.53)$], [$bold(+0.16)$], [$bold(+1.18)$], [$bold(+0.22)$],
      [`global_only`], [$+0.40$], [$+0.39$], [$+0.34$], [$+0.95$], [$+0.25$], [$-0.09$], [$+0.73$], [$+0.11$],
      [`all_free`], [$+0.21$], [$+0.36$], [$+0.21$], [$bold(+1.44)$], [$-0.22$], [$+0.03$], [$+0.80$], [$-0.11$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[WordNet]], table.cell(rowspan: 5)[euc], [`all_off`], [$99.8$], [$54.5$], [$57.3$], [$177$], [$180$], [$65.0$], [$118$], [$118$],
      [`centering_only`], [$-0.21$], [$-0.12$], [$-0.11$], [$-0.71$], [$-0.04$], [$-0.16$], [$-0.25$], [$-0.25$],
      [`global_only`], [$-0.77$], [$-0.28$], [$-0.55$], [$-1.04$], [$-0.56$], [$-0.34$], [$-0.73$], [$-0.73$],
      [`norm_only`], [$+0.67$], [$+0.29$], [$+0.38$], [$+1.83$], [$+0.37$], [$+0.17$], [$+0.72$], [$+0.72$],
      [`all_free`], [$bold(+2.81)$], [$bold(+1.09)$], [$bold(+2.01)$], [$bold(+1.86)$], [$bold(+4.11)$], [$bold(+1.62)$], [$bold(+2.70)$], [$bold(+2.70)$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[WordNet]], table.cell(rowspan: 5)[hyp], [`all_off`], [$81.4$], [$44.3$], [$46.2$], [$139$], [$148$], [$54.8$], [$67.7$], [$118$],
      [`centering_only`], [$+1.16$], [$+0.30$], [$+1.01$], [$-0.33$], [$+0.98$], [$+0.47$], [$-0.81$], [$+2.87$],
      [`global_only`], [$-2.37$], [$-1.13$], [$-1.50$], [$-2.37$], [$-4.89$], [$-1.35$], [$-4.47$], [$-1.28$],
      [`norm_only`], [$bold(+1.40)$], [$bold(+0.44)$], [$bold(+1.06)$], [$bold(+1.08)$], [$bold(+2.52)$], [$bold(+0.80)$], [$-0.67$], [$bold(+2.92)$],
      [`all_free`], [$-1.00$], [$-0.95$], [$-0.39$], [$-2.22$], [$-2.00$], [$-0.48$], [$-7.62$], [$+2.91$],
      table.hline(stroke: 0.8pt),
    ),
    caption: [Experiment 2: R2 indicator gain $Delta R_2$ of each loss-weight setting over the
    `all_off` baseline on the real datasets, under each preference region of @preference-regions
    ($N = 1000$).

    Every entry is multiplied by $1000$, so a table entry of $1$ is an indicator value
    of $10^(-3)$.
    The `all_off` row opening each geometry block is the baseline *level* $R_2$ of that front
    (@eq:r2), a cost: smaller is better.  Every row below it is the *gain*
    $Delta R_2 = R_2("all_off") - R_2("setting")$ of @eq:r2-gain, formed
    baseline-minus-setting so that a positive value means the setting improved on the
    baseline.  Levels are therefore unsigned and gains always carry a sign.
    Within each geometry block the largest positive gain per region is set in bold; a block
    with no positive gain has no bold entry.  An entry of $approx 0$ is a gain below the
    resolution printed here, where the front barely moved and the sign carries nothing.

    The columns are the weight sets of @preference-regions: $W_"all"$ is the full simplex and
    is the only one under which $Delta R_2$ is a claim about overall front quality; the five
    per-metric regions hold the weight vectors placing at least half their mass on that
    metric's two objectives; $W_"man"$ and $W_"proj"$ hold those supported entirely on the
    five manifold, respectively the five projected, objectives.  A setting that helps under
    one priority and costs under another is visible as a sign change along its row.

    `norm_only` is absent from every spherical block because the depth-norm loss is
    undefined on the sphere (@norm-loss).  `rms_anchored` is not an ablation of a loss term
    and is reported with the curvature results (@curvature-magnitude-results) instead.
  ],
  ) <tab:r2-delta-real-n1000>
]
