// Generated by scripts/r2_delta_typst.py -- do not edit by hand.
#[
  #show figure: set block(breakable: true)
  #figure(
    table(
      columns: 11,
      align: (left, left, left, right, right, right, right, right, right, right, right),
      stroke: none,
      inset: (x: 2.5pt, y: 3pt),
      table.hline(stroke: 0.8pt),
      table.header(
        table.cell(rowspan: 2, align: horizon)[*Dataset*], table.cell(rowspan: 2, align: horizon)[*Geom.*], table.cell(rowspan: 2, align: horizon)[*Setting*], table.cell(rowspan: 2, align: horizon + right)[$W_"all"$], table.cell(colspan: 5, align: center)[*Per-metric*], table.cell(colspan: 2, align: center)[*Surface*],
        [$W_"trust"$], [$W_"cont"$], [$W_"stress"$], [$W_"shep"$], [$W_"nh"$], [$W_"man"$], [$W_"proj"$],
      ),
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[grid], table.cell(rowspan: 4)[sph], [`all_off`], [$17.4$], [$8.73$], [$8.56$], [$28.7$], [$11.2$], [$30.9$], [$20.9$], [$17.8$],
      [`centering_only`], [$+0.23$], [$+0.16$], [$+0.21$], [$+0.98$], [$+0.08$], [$-0.14$], [$-0.09$], [$+1.10$],
      [`global_only`], [$+0.27$], [$+0.12$], [$+0.13$], [$+0.32$], [$+0.14$], [$bold(+0.67)$], [$+0.04$], [$bold(+1.12)$],
      [`all_free`], [$bold(+0.43)$], [$bold(+0.29)$], [$bold(+0.23)$], [$bold(+1.00)$], [$bold(+0.20)$], [$+0.44$], [$bold(+0.31)$], [$+0.98$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[grid]], table.cell(rowspan: 5)[euc], [`all_off`], [$19.4$], [$10.3$], [$10.3$], [$29.9$], [$11.6$], [$40.7$], [$22.9$], [$22.9$],
      [`centering_only`], [$+0.05$], [$+0.04$], [$+0.04$], [$+0.01$], [$+0.01$], [$+0.26$], [$+0.07$], [$+0.07$],
      [`global_only`], [$+1.01$], [$+0.62$], [$+0.97$], [$-0.39$], [$-0.07$], [$+7.00$], [$+1.58$], [$+1.58$],
      [`norm_only`], [$+1.10$], [$+0.93$], [$+1.05$], [$-0.57$], [$-0.16$], [$+7.86$], [$+1.72$], [$+1.72$],
      [`all_free`], [$bold(+1.48)$], [$bold(+1.23)$], [$bold(+1.42)$], [$bold(+0.16)$], [$bold(+0.11)$], [$bold(+8.26)$], [$bold(+2.18)$], [$bold(+2.18)$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[grid]], table.cell(rowspan: 5)[hyp], [`all_off`], [$17.0$], [$9.02$], [$8.47$], [$30.4$], [$11.3$], [$27.3$], [$19.3$], [$19.7$],
      [`centering_only`], [$bold(+0.56)$], [$bold(+0.12)$], [$bold(+0.27)$], [$bold(+2.74)$], [$bold(+0.64)$], [$-0.17$], [$bold(+0.19)$], [$bold(+4.01)$],
      [`global_only`], [$-0.03$], [$-0.14$], [$+0.06$], [$+0.52$], [$+0.08$], [$-0.81$], [$+0.03$], [$-0.07$],
      [`norm_only`], [$+0.02$], [$+0.11$], [$approx 0$], [$+0.30$], [$-0.11$], [$bold(+0.33)$], [$+0.18$], [$-0.02$],
      [`all_free`], [$approx 0$], [$-0.04$], [$-0.09$], [$+1.64$], [$+0.29$], [$-0.94$], [$-0.46$], [$+3.88$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[sphere], table.cell(rowspan: 4)[sph], [`all_off`], [$150$], [$99.1$], [$111$], [$171$], [$304$], [$147$], [$166$], [$199$],
      [`centering_only`], [$bold(+3.01)$], [$bold(+3.24)$], [$bold(+2.92)$], [$-4.35$], [$bold(+7.18)$], [$+4.27$], [$+2.09$], [$bold(+2.88)$],
      [`global_only`], [$+1.67$], [$+2.78$], [$+2.66$], [$-3.78$], [$+6.91$], [$-4.51$], [$+0.86$], [$+0.66$],
      [`all_free`], [$+2.48$], [$+1.14$], [$+2.75$], [$-0.19$], [$+3.79$], [$bold(+5.01)$], [$bold(+5.93)$], [$+0.06$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[sphere]], table.cell(rowspan: 5)[euc], [`all_off`], [$163$], [$101$], [$121$], [$210$], [$327$], [$153$], [$200$], [$200$],
      [`centering_only`], [$+0.27$], [$+0.30$], [$+0.36$], [$+0.05$], [$+0.39$], [$+0.89$], [$+0.43$], [$+0.43$],
      [`global_only`], [$+0.22$], [$+0.29$], [$+0.13$], [$-0.29$], [$-0.86$], [$+3.79$], [$+0.53$], [$+0.53$],
      [`norm_only`], [$bold(+2.22)$], [$bold(+1.05)$], [$bold(+0.71)$], [$bold(+0.69)$], [$bold(+4.06)$], [$bold(+5.09)$], [$bold(+2.58)$], [$bold(+2.58)$],
      [`all_free`], [$+0.04$], [$-7.57$], [$+0.08$], [$+0.30$], [$+1.35$], [$+1.65$], [$-0.78$], [$-0.78$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[sphere]], table.cell(rowspan: 5)[hyp], [`all_off`], [$155$], [$97.8$], [$120$], [$171$], [$325$], [$147$], [$181$], [$197$],
      [`centering_only`], [$-3.37$], [$-0.69$], [$bold(+1.32)$], [$+0.78$], [$-2.55$], [$-23.6$], [$-3.37$], [$-6.19$],
      [`global_only`], [$-0.67$], [$-0.38$], [$-0.76$], [$-2.03$], [$-5.21$], [$bold(+7.74)$], [$+0.31$], [$-1.03$],
      [`norm_only`], [$bold(+0.41)$], [$approx 0$], [$+1.30$], [$bold(+0.94)$], [$bold(+2.35)$], [$-6.95$], [$bold(+1.08)$], [$-1.04$],
      [`all_free`], [$+0.14$], [$-0.81$], [$+0.99$], [$+0.25$], [$+0.16$], [$-2.90$], [$-1.16$], [$bold(+1.44)$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[antipodal], table.cell(rowspan: 4)[sph], [`all_off`], [$50.2$], [$45.1$], [$46.8$], [$82.3$], [$80.7$], [$29.3$], [$56.8$], [$66.3$],
      [`centering_only`], [$bold(+1.34)$], [$+0.40$], [$bold(+0.38)$], [$-0.38$], [$+6.74$], [$bold(+0.88)$], [$bold(+1.25)$], [$+2.14$],
      [`global_only`], [$+1.13$], [$+0.08$], [$-0.13$], [$-1.28$], [$bold(+9.80)$], [$+0.46$], [$-0.56$], [$bold(+4.02)$],
      [`all_free`], [$+0.52$], [$bold(+0.47)$], [$-0.29$], [$-2.34$], [$+5.92$], [$+0.20$], [$-1.18$], [$+2.70$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[antipodal]], table.cell(rowspan: 5)[euc], [`all_off`], [$53.9$], [$46.3$], [$47.7$], [$93.5$], [$86.5$], [$31.2$], [$66.4$], [$66.4$],
      [`centering_only`], [$bold(+0.15)$], [$+0.11$], [$bold(+0.05)$], [$bold(+0.16)$], [$+0.16$], [$+0.01$], [$+0.12$], [$+0.12$],
      [`global_only`], [$-0.08$], [$+0.26$], [$-1.42$], [$+0.15$], [$+0.15$], [$-0.01$], [$-0.17$], [$-0.17$],
      [`norm_only`], [$+0.05$], [$+0.01$], [$-0.21$], [$+0.14$], [$+0.14$], [$-0.01$], [$+0.02$], [$+0.02$],
      [`all_free`], [$+0.14$], [$bold(+0.61)$], [$-0.29$], [$+0.15$], [$bold(+0.22)$], [$bold(+0.06)$], [$bold(+0.15)$], [$bold(+0.15)$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[antipodal]], table.cell(rowspan: 5)[hyp], [`all_off`], [$51.9$], [$45.0$], [$47.5$], [$82.6$], [$87.7$], [$30.2$], [$61.2$], [$66.4$],
      [`centering_only`], [$bold(+1.13)$], [$-0.18$], [$-0.28$], [$bold(+6.49)$], [$bold(+1.76)$], [$bold(+0.52)$], [$bold(+2.81)$], [$bold(+0.77)$],
      [`global_only`], [$-0.85$], [$-0.36$], [$-0.47$], [$-2.98$], [$-0.58$], [$-0.42$], [$-1.39$], [$-0.70$],
      [`norm_only`], [$+0.28$], [$-0.87$], [$-0.28$], [$+1.07$], [$+1.50$], [$+0.27$], [$+0.67$], [$+0.04$],
      [`all_free`], [$+0.10$], [$-0.74$], [$-0.68$], [$+4.43$], [$+0.04$], [$+0.11$], [$+1.30$], [$+0.37$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[tree], table.cell(rowspan: 4)[sph], [`all_off`], [$78.6$], [$43.3$], [$49.9$], [$167$], [$118$], [$43.8$], [$90.6$], [$95.9$],
      [`centering_only`], [$-2.05$], [$-1.04$], [$-0.99$], [$-6.66$], [$-0.91$], [$-1.00$], [$-4.65$], [$-0.30$],
      [`global_only`], [$-0.64$], [$-0.27$], [$-0.33$], [$-1.59$], [$-0.90$], [$-0.28$], [$-1.22$], [$-0.31$],
      [`all_free`], [$-1.45$], [$-0.68$], [$-0.66$], [$-5.16$], [$-0.08$], [$-0.75$], [$-3.41$], [$-0.04$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[tree]], table.cell(rowspan: 5)[euc], [`all_off`], [$80.9$], [$44.4$], [$51.0$], [$175$], [$118$], [$45.0$], [$96.1$], [$96.1$],
      [`centering_only`], [$+0.01$], [$+0.01$], [$+0.07$], [$approx 0$], [$-0.01$], [$+0.02$], [$+0.01$], [$+0.01$],
      [`global_only`], [$-0.16$], [$-0.06$], [$-0.02$], [$-0.11$], [$-0.65$], [$-0.01$], [$-0.19$], [$-0.19$],
      [`norm_only`], [$bold(+15.6)$], [$bold(+8.95)$], [$+7.66$], [$+13.3$], [$bold(+51.8)$], [$+9.10$], [$bold(+19.3)$], [$bold(+19.3)$],
      [`all_free`], [$+15.6$], [$+8.91$], [$bold(+7.67)$], [$bold(+13.3)$], [$+51.8$], [$bold(+9.10)$], [$+19.3$], [$+19.3$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[tree]], table.cell(rowspan: 5)[hyp], [`all_off`], [$57.7$], [$31.0$], [$36.0$], [$123$], [$82.4$], [$31.7$], [$30.7$], [$95.3$],
      [`centering_only`], [$-7.10$], [$-5.26$], [$-3.79$], [$-6.69$], [$-19.9$], [$-4.35$], [$-19.5$], [$-2.84$],
      [`global_only`], [$+0.45$], [$+0.28$], [$+0.23$], [$-0.32$], [$+2.44$], [$+0.26$], [$-0.27$], [$+1.35$],
      [`norm_only`], [$+2.08$], [$+1.24$], [$bold(+1.12)$], [$+1.83$], [$+6.27$], [$bold(+0.82)$], [$bold(+0.71)$], [$+4.19$],
      [`all_free`], [$bold(+2.74)$], [$bold(+1.32)$], [$+0.99$], [$bold(+2.29)$], [$bold(+12.1)$], [$+0.70$], [$-10.4$], [$bold(+17.4)$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[hyp. shells], table.cell(rowspan: 4)[sph], [`all_off`], [$135$], [$108$], [$104$], [$229$], [$173$], [$131$], [$157$], [$173$],
      [`centering_only`], [$bold(+2.05)$], [$bold(+0.51)$], [$bold(+0.76)$], [$bold(+2.35)$], [$bold(+8.37)$], [$bold(+4.04)$], [$bold(+2.25)$], [$bold(+3.77)$],
      [`global_only`], [$-21.8$], [$-3.96$], [$-5.71$], [$-0.20$], [$-1.93$], [$-111$], [$-26.2$], [$-26.0$],
      [`all_free`], [$-22.7$], [$-3.86$], [$-7.53$], [$-5.80$], [$+1.16$], [$-113$], [$-30.1$], [$-24.6$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[hyp. shells]], table.cell(rowspan: 5)[euc], [`all_off`], [$168$], [$189$], [$117$], [$239$], [$293$], [$134$], [$211$], [$211$],
      [`centering_only`], [$+0.47$], [$+1.67$], [$-0.23$], [$-1.16$], [$+1.45$], [$+1.37$], [$+0.61$], [$+0.61$],
      [`global_only`], [$+0.62$], [$+0.55$], [$-0.04$], [$-1.30$], [$+1.30$], [$+4.52$], [$+0.99$], [$+0.99$],
      [`norm_only`], [$bold(+47.2)$], [$bold(+4.35)$], [$bold(+17.8)$], [$bold(+62.8)$], [$+131$], [$+58.6$], [$bold(+60.1)$], [$bold(+60.1)$],
      [`all_free`], [$+46.7$], [$-0.18$], [$+16.4$], [$+62.6$], [$bold(+134)$], [$bold(+59.4)$], [$+59.7$], [$+59.7$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[hyp. shells]], table.cell(rowspan: 5)[hyp], [`all_off`], [$127$], [$109$], [$96.8$], [$199$], [$168$], [$126$], [$130$], [$175$],
      [`centering_only`], [$-33.3$], [$-4.46$], [$-15.1$], [$-38.8$], [$-10.5$], [$-126$], [$-65.8$], [$-25.3$],
      [`global_only`], [$-19.5$], [$-3.21$], [$-5.62$], [$-10.4$], [$-6.02$], [$-94.4$], [$-26.5$], [$-24.6$],
      [`norm_only`], [$bold(+20.2)$], [$-0.15$], [$bold(+9.21)$], [$+27.2$], [$+21.3$], [$+52.0$], [$bold(+24.4)$], [$+24.9$],
      [`all_free`], [$+19.4$], [$-47.0$], [$+3.01$], [$bold(+27.9)$], [$bold(+52.4)$], [$bold(+52.5)$], [$+8.91$], [$bold(+28.9)$],
      table.hline(stroke: 0.8pt),
    ),
    caption: [Experiment 2: R2 indicator gain $Delta R_2$ of each loss-weight setting over the
    `all_off` baseline on the synthetic datasets of known intrinsic geometry, under each preference region of @preference-regions
    ($N = 1000$).

    Every entry is multiplied by $1000$, so a table entry of $1$ is an indicator value
    of $10^(-3)$.
    The `all_off` row opening each geometry block is the baseline *level* $R_2$ of that front
    (@eq:r2), a cost: smaller is better.  Every row below it is the *gain*
    $Delta R_2 = R_2("all_off") - R_2("setting")$ of @eq:r2-gain, formed
    baseline-minus-setting so that a positive value means the setting improved on the
    baseline.  Levels are therefore unsigned and gains always carry a sign.
    Within each geometry block the largest positive gain per region is set in bold; a block
    with no positive gain has no bold entry.  An entry of $approx 0$ is a gain below the
    resolution printed here, where the front barely moved and the sign carries nothing.

    The columns are the weight sets of @preference-regions: $W_"all"$ is the full simplex and
    is the only one under which $Delta R_2$ is a claim about overall front quality; the five
    per-metric regions hold the weight vectors placing at least half their mass on that
    metric's two objectives; $W_"man"$ and $W_"proj"$ hold those supported entirely on the
    five manifold, respectively the five projected, objectives.  A setting that helps under
    one priority and costs under another is visible as a sign change along its row.

    `norm_only` is absent from every spherical block because the depth-norm loss is
    undefined on the sphere (@norm-loss).  `rms_anchored` is not an ablation of a loss term
    and is reported with the curvature results (@curvature-magnitude-results) instead.
  ],
  ) <tab:r2-delta-synthetic-n1000>
]
