// Generated by scripts/r2_delta_typst.py -- do not edit by hand.
#[
  #show figure: set block(breakable: true)
  #figure(
    table(
      columns: 11,
      align: (left, left, left, right, right, right, right, right, right, right, right),
      stroke: none,
      inset: (x: 2.5pt, y: 3pt),
      table.hline(stroke: 0.8pt),
      table.header(
        table.cell(rowspan: 2, align: horizon)[*Dataset*], table.cell(rowspan: 2, align: horizon)[*Geom.*], table.cell(rowspan: 2, align: horizon)[*Setting*], table.cell(rowspan: 2, align: horizon + right)[$W_"all"$], table.cell(colspan: 5, align: center)[*Per-metric*], table.cell(colspan: 2, align: center)[*Surface*],
        [$W_"trust"$], [$W_"cont"$], [$W_"stress"$], [$W_"shep"$], [$W_"nh"$], [$W_"man"$], [$W_"proj"$],
      ),
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[MNIST], table.cell(rowspan: 4)[sph], [`all_off`], [$113$], [$67.9$], [$65.8$], [$158$], [$222$], [$89.9$], [$127$], [$143$],
      [`centering_only`], [$-0.76$], [$-0.60$], [$-0.41$], [$-0.91$], [$-0.07$], [$-1.04$], [$-0.32$], [$-1.23$],
      [`global_only`], [$-3.16$], [$-2.52$], [$-1.77$], [$-10.2$], [$-1.52$], [$-1.20$], [$-3.82$], [$-2.05$],
      [`all_free`], [$-1.76$], [$-1.02$], [$-1.09$], [$-2.40$], [$-1.30$], [$-1.01$], [$-2.06$], [$-1.34$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[MNIST]], table.cell(rowspan: 5)[euc], [`all_off`], [$120$], [$69.3$], [$69.1$], [$203$], [$223$], [$90.7$], [$144$], [$144$],
      [`centering_only`], [$+0.11$], [$+0.09$], [$+0.03$], [$+0.23$], [$-0.18$], [$+0.30$], [$+0.09$], [$+0.09$],
      [`global_only`], [$-0.56$], [$+0.05$], [$-0.14$], [$-2.33$], [$-0.62$], [$bold(+2.04)$], [$-0.35$], [$-0.35$],
      [`norm_only`], [$+16.1$], [$+6.03$], [$+9.06$], [$+0.79$], [$+79.4$], [$-0.92$], [$+20.1$], [$+20.1$],
      [`all_free`], [$bold(+16.6)$], [$bold(+6.58)$], [$bold(+9.26)$], [$bold(+1.18)$], [$bold(+80.0)$], [$+1.89$], [$bold(+21.0)$], [$bold(+21.0)$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[MNIST]], table.cell(rowspan: 5)[hyp], [`all_off`], [$108$], [$63.4$], [$62.6$], [$152$], [$216$], [$86.4$], [$111$], [$145$],
      [`centering_only`], [$-1.90$], [$-1.18$], [$-0.67$], [$bold(+0.51)$], [$-4.80$], [$-2.43$], [$-4.08$], [$+0.03$],
      [`global_only`], [$-0.76$], [$bold(+0.25)$], [$-0.36$], [$-2.53$], [$-1.56$], [$-0.25$], [$-0.92$], [$-0.75$],
      [`norm_only`], [$-2.33$], [$-1.21$], [$-1.30$], [$-1.60$], [$-7.39$], [$-1.46$], [$-5.54$], [$-0.13$],
      [`all_free`], [$-7.90$], [$-4.88$], [$-4.95$], [$-3.81$], [$-20.8$], [$-3.36$], [$-17.6$], [$bold(+0.17)$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[F-MNIST], table.cell(rowspan: 4)[sph], [`all_off`], [$85.6$], [$50.0$], [$48.5$], [$129$], [$83.4$], [$161$], [$100$], [$108$],
      [`centering_only`], [$+0.12$], [$+0.12$], [$+0.12$], [$bold(+0.03)$], [$bold(+0.25)$], [$+0.49$], [$+0.09$], [$+0.30$],
      [`global_only`], [$bold(+0.92)$], [$bold(+0.44)$], [$bold(+0.58)$], [$-0.17$], [$-0.11$], [$bold(+5.68)$], [$bold(+1.12)$], [$bold(+1.42)$],
      [`all_free`], [$+0.83$], [$+0.41$], [$+0.47$], [$-0.32$], [$-0.33$], [$+5.52$], [$+0.93$], [$+1.34$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[F-MNIST]], table.cell(rowspan: 5)[euc], [`all_off`], [$89.0$], [$51.6$], [$50.6$], [$146$], [$84.8$], [$161$], [$108$], [$108$],
      [`centering_only`], [$+0.13$], [$+0.08$], [$+0.06$], [$-0.10$], [$-0.02$], [$+0.68$], [$+0.15$], [$+0.15$],
      [`global_only`], [$+0.42$], [$+0.22$], [$+0.23$], [$-0.26$], [$-0.41$], [$bold(+3.22)$], [$+0.58$], [$+0.58$],
      [`norm_only`], [$bold(+2.69)$], [$bold(+1.65)$], [$bold(+1.93)$], [$bold(+1.64)$], [$bold(+11.8)$], [$+1.37$], [$bold(+3.75)$], [$bold(+3.75)$],
      [`all_free`], [$+1.28$], [$+0.96$], [$+0.99$], [$-2.27$], [$+9.05$], [$+2.26$], [$+2.08$], [$+2.08$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[F-MNIST]], table.cell(rowspan: 5)[hyp], [`all_off`], [$83.2$], [$48.3$], [$47.4$], [$121$], [$84.3$], [$158$], [$93.3$], [$107$],
      [`centering_only`], [$bold(+0.47)$], [$bold(+0.05)$], [$bold(+0.17)$], [$bold(+4.01)$], [$bold(+1.32)$], [$-1.27$], [$bold(+0.92)$], [$bold(+0.32)$],
      [`global_only`], [$-0.69$], [$-0.39$], [$-0.37$], [$-1.74$], [$-1.62$], [$bold(+0.50)$], [$-0.72$], [$-0.86$],
      [`norm_only`], [$-0.36$], [$-0.38$], [$-0.28$], [$-0.44$], [$-1.28$], [$-0.35$], [$-0.64$], [$-0.61$],
      [`all_free`], [$-0.32$], [$-0.59$], [$-0.31$], [$+1.00$], [$-0.86$], [$-0.19$], [$-0.46$], [$-0.72$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[PBMC], table.cell(rowspan: 4)[sph], [`all_off`], [$97.8$], [$77.0$], [$62.9$], [$198$], [$143$], [$56.1$], [$116$], [$120$],
      [`centering_only`], [$bold(+0.76)$], [$bold(+0.39)$], [$bold(+0.78)$], [$bold(+1.50)$], [$bold(+1.72)$], [$bold(+0.49)$], [$+1.26$], [$bold(+0.89)$],
      [`global_only`], [$-0.11$], [$-0.54$], [$+0.25$], [$-0.31$], [$+0.16$], [$-0.13$], [$+0.12$], [$-0.48$],
      [`all_free`], [$+0.50$], [$-0.01$], [$+0.62$], [$+0.70$], [$+1.28$], [$+0.39$], [$bold(+1.33)$], [$-0.06$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[PBMC]], table.cell(rowspan: 5)[euc], [`all_off`], [$101$], [$77.5$], [$63.7$], [$209$], [$143$], [$57.5$], [$121$], [$121$],
      [`centering_only`], [$-0.05$], [$-0.45$], [$-0.08$], [$+0.13$], [$-0.08$], [$-0.07$], [$-0.12$], [$-0.12$],
      [`global_only`], [$-0.95$], [$-0.35$], [$-0.68$], [$-2.86$], [$-0.49$], [$-0.54$], [$-1.12$], [$-1.12$],
      [`norm_only`], [$bold(+27.2)$], [$bold(+8.24)$], [$bold(+11.0)$], [$+34.5$], [$bold(+88.5)$], [$bold(+15.8)$], [$bold(+33.9)$], [$bold(+33.9)$],
      [`all_free`], [$+26.4$], [$+4.28$], [$+9.71$], [$bold(+35.1)$], [$+88.2$], [$+15.5$], [$+32.9$], [$+32.9$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[PBMC]], table.cell(rowspan: 5)[hyp], [`all_off`], [$92.3$], [$73.3$], [$58.9$], [$181$], [$139$], [$52.9$], [$98.3$], [$121$],
      [`centering_only`], [$+2.92$], [$bold(+0.58)$], [$bold(+1.22)$], [$bold(+1.90)$], [$+10.5$], [$+1.57$], [$+2.88$], [$+4.29$],
      [`global_only`], [$-0.87$], [$-0.83$], [$-0.56$], [$-2.83$], [$-0.39$], [$-0.57$], [$-2.33$], [$-0.18$],
      [`norm_only`], [$+0.50$], [$+0.02$], [$+0.12$], [$+1.70$], [$+0.05$], [$+0.24$], [$+0.07$], [$+0.85$],
      [`all_free`], [$bold(+4.18)$], [$-0.39$], [$+1.06$], [$+1.83$], [$bold(+17.5)$], [$bold(+2.34)$], [$bold(+3.11)$], [$bold(+5.84)$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[WordNet], table.cell(rowspan: 4)[sph], [`all_off`], [$84.0$], [$46.5$], [$47.3$], [$164$], [$144$], [$54.2$], [$101$], [$100$],
      [`centering_only`], [$bold(+0.55)$], [$bold(+0.28)$], [$bold(+0.31)$], [$bold(+1.18)$], [$bold(+1.20)$], [$bold(+0.06)$], [$bold(+0.92)$], [$bold(+0.43)$],
      [`global_only`], [$+0.14$], [$+0.12$], [$+0.12$], [$+0.82$], [$+0.45$], [$-0.19$], [$+0.75$], [$-0.28$],
      [`all_free`], [$-0.89$], [$-0.36$], [$-0.46$], [$-1.07$], [$-2.24$], [$-0.17$], [$-1.10$], [$-0.89$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[WordNet]], table.cell(rowspan: 5)[euc], [`all_off`], [$84.0$], [$46.5$], [$47.3$], [$165$], [$143$], [$54.2$], [$101$], [$101$],
      [`centering_only`], [$+0.17$], [$+0.12$], [$+0.08$], [$+0.39$], [$+0.14$], [$+0.20$], [$+0.20$], [$+0.20$],
      [`global_only`], [$-0.32$], [$-0.10$], [$-0.14$], [$-0.83$], [$-0.30$], [$-0.21$], [$-0.36$], [$-0.36$],
      [`norm_only`], [$+1.80$], [$+0.98$], [$+0.93$], [$+2.00$], [$+5.40$], [$bold(+0.60)$], [$+2.18$], [$+2.18$],
      [`all_free`], [$bold(+1.89)$], [$bold(+1.09)$], [$bold(+1.02)$], [$bold(+2.12)$], [$bold(+5.83)$], [$+0.52$], [$bold(+2.30)$], [$bold(+2.30)$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[WordNet]], table.cell(rowspan: 5)[hyp], [`all_off`], [$69.1$], [$38.0$], [$38.4$], [$131$], [$116$], [$46.7$], [$56.9$], [$101$],
      [`centering_only`], [$+0.11$], [$bold(+0.25)$], [$bold(+0.22)$], [$-0.72$], [$-0.45$], [$+0.20$], [$-1.30$], [$+1.85$],
      [`global_only`], [$-3.25$], [$-1.73$], [$-1.77$], [$-3.45$], [$-10.8$], [$-1.44$], [$-4.95$], [$-3.36$],
      [`norm_only`], [$-0.63$], [$-0.60$], [$-0.61$], [$-2.28$], [$-0.13$], [$+0.15$], [$-4.60$], [$+1.29$],
      [`all_free`], [$bold(+0.42)$], [$+0.03$], [$-0.13$], [$-0.54$], [$bold(+2.00)$], [$bold(+0.88)$], [$-4.38$], [$bold(+3.68)$],
      table.hline(stroke: 0.8pt),
    ),
    caption: [Experiment 2: R2 indicator gain $Delta R_2$ of each loss-weight setting over the
    `all_off` baseline on the real datasets, under each preference region of @preference-regions
    ($N = 5000$).

    Every entry is multiplied by $1000$, so a table entry of $1$ is an indicator value
    of $10^(-3)$.
    The `all_off` row opening each geometry block is the baseline *level* $R_2$ of that front
    (@eq:r2), a cost: smaller is better.  Every row below it is the *gain*
    $Delta R_2 = R_2("all_off") - R_2("setting")$ of @eq:r2-gain, formed
    baseline-minus-setting so that a positive value means the setting improved on the
    baseline.  Levels are therefore unsigned and gains always carry a sign.
    Within each geometry block the largest positive gain per region is set in bold; a block
    with no positive gain has no bold entry.  An entry of $approx 0$ is a gain below the
    resolution printed here, where the front barely moved and the sign carries nothing.

    The columns are the weight sets of @preference-regions: $W_"all"$ is the full simplex and
    is the only one under which $Delta R_2$ is a claim about overall front quality; the five
    per-metric regions hold the weight vectors placing at least half their mass on that
    metric's two objectives; $W_"man"$ and $W_"proj"$ hold those supported entirely on the
    five manifold, respectively the five projected, objectives.  A setting that helps under
    one priority and costs under another is visible as a sign change along its row.

    `norm_only` is absent from every spherical block because the depth-norm loss is
    undefined on the sphere (@norm-loss).  `rms_anchored` is not an ablation of a loss term
    and is reported with the curvature results (@curvature-magnitude-results) instead.
  ],
  ) <tab:r2-delta-real-n5000>
]
