// Generated by scripts/r2_delta_typst.py -- do not edit by hand.
#[
  #show figure: set block(breakable: true)
  #figure(
    table(
      columns: 11,
      align: (left, left, left, right, right, right, right, right, right, right, right),
      stroke: none,
      inset: (x: 2.5pt, y: 3pt),
      table.hline(stroke: 0.8pt),
      table.header(
        table.cell(rowspan: 2, align: horizon)[*Dataset*], table.cell(rowspan: 2, align: horizon)[*Geom.*], table.cell(rowspan: 2, align: horizon)[*Setting*], table.cell(rowspan: 2, align: horizon + right)[$W_"all"$], table.cell(colspan: 2, align: center)[*Family*], table.cell(colspan: 5, align: center)[*Per-objective*],
        [$W_"struct"$], [$W_"dist"$], [$W_"trust"$], [$W_"cont"$], [$W_"stress"$], [$W_"shep"$], [$W_"nh"$],
      ),
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[grid], table.cell(rowspan: 4)[sph], [`all_off`], [$7.89$], [$3.91$], [$8.35$], [$3.40$], [$3.36$], [$13.5$], [$3.95$], [$16.4$],
      [`centering_only`], [$bold(+0.86)$], [$bold(+0.52)$], [$bold(+2.02)$], [$bold(+0.47)$], [$bold(+0.46)$], [$bold(+4.25)$], [$bold(+0.57)$], [$-0.27$],
      [`global_only`], [$-0.06$], [$+0.17$], [$-0.60$], [$+0.17$], [$+0.15$], [$-0.98$], [$-0.32$], [$bold(+1.54)$],
      [`all_free`], [$+0.47$], [$+0.38$], [$+0.86$], [$+0.29$], [$+0.36$], [$+1.78$], [$+0.24$], [$+0.59$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[grid]], table.cell(rowspan: 5)[euc], [`all_off`], [$11.7$], [$5.88$], [$15.1$], [$5.11$], [$5.11$], [$26.2$], [$6.27$], [$19.2$],
      [`centering_only`], [$-0.01$], [$-0.01$], [$-0.02$], [$-0.01$], [$-0.01$], [$-0.03$], [$-0.01$], [$+0.01$],
      [`global_only`], [$+0.01$], [$+0.03$], [$-0.41$], [$-0.07$], [$+0.12$], [$-0.74$], [$-0.16$], [$+1.49$],
      [`norm_only`], [$bold(+0.31)$], [$bold(+0.28)$], [$-0.06$], [$bold(+0.20)$], [$bold(+0.28)$], [$-0.11$], [$-0.03$], [$bold(+1.96)$],
      [`all_free`], [$+0.25$], [$+0.23$], [$-0.12$], [$+0.11$], [$+0.26$], [$-0.20$], [$-0.06$], [$+1.87$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[grid]], table.cell(rowspan: 5)[hyp], [`all_off`], [$11.1$], [$5.45$], [$15.4$], [$4.90$], [$4.64$], [$26.8$], [$6.37$], [$14.3$],
      [`centering_only`], [$bold(+2.58)$], [$+1.34$], [$bold(+5.18)$], [$+1.22$], [$+1.13$], [$bold(+9.90)$], [$bold(+1.73)$], [$bold(+0.42)$],
      [`global_only`], [$-0.05$], [$-0.06$], [$approx 0$], [$-0.06$], [$-0.04$], [$+0.01$], [$-0.02$], [$-0.17$],
      [`norm_only`], [$+0.15$], [$+0.09$], [$+0.13$], [$+0.16$], [$+0.07$], [$+0.22$], [$+0.07$], [$+0.35$],
      [`all_free`], [$+2.52$], [$bold(+1.35)$], [$+5.16$], [$bold(+1.30)$], [$bold(+1.17)$], [$+9.89$], [$+1.69$], [$+0.01$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[sphere], table.cell(rowspan: 4)[sph], [`all_off`], [$198$], [$123$], [$295$], [$116$], [$124$], [$264$], [$413$], [$185$],
      [`centering_only`], [$bold(+1.33)$], [$bold(+0.32)$], [$+2.51$], [$-0.55$], [$bold(+0.28)$], [$+0.57$], [$+5.00$], [$bold(+0.29)$],
      [`global_only`], [$-6.13$], [$-2.57$], [$-5.88$], [$-1.72$], [$-2.49$], [$-2.93$], [$-10.4$], [$-18.7$],
      [`all_free`], [$+0.41$], [$-0.09$], [$bold(+2.94)$], [$-0.23$], [$-0.78$], [$bold(+0.91)$], [$bold(+5.69)$], [$-6.52$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[sphere]], table.cell(rowspan: 5)[euc], [`all_off`], [$197$], [$123$], [$295$], [$116$], [$126$], [$264$], [$414$], [$182$],
      [`centering_only`], [$-5.25$], [$-1.47$], [$-0.04$], [$-0.44$], [$-1.11$], [$-0.01$], [$-0.04$], [$-33.3$],
      [`global_only`], [$-3.09$], [$-2.17$], [$-1.87$], [$-4.46$], [$-0.44$], [$-1.07$], [$-3.10$], [$-11.9$],
      [`norm_only`], [$bold(+3.98)$], [$bold(+1.03)$], [$bold(+1.62)$], [$bold(+0.75)$], [$bold(+0.37)$], [$bold(+0.36)$], [$bold(+3.26)$], [$bold(+20.9)$],
      [`all_free`], [$+2.18$], [$+0.08$], [$-0.46$], [$-0.31$], [$-0.08$], [$-0.22$], [$-0.77$], [$+16.7$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[sphere]], table.cell(rowspan: 5)[hyp], [`all_off`], [$198$], [$123$], [$292$], [$115$], [$126$], [$264$], [$407$], [$193$],
      [`centering_only`], [$-0.56$], [$+1.74$], [$+0.33$], [$+4.62$], [$+0.75$], [$bold(+0.49)$], [$+0.20$], [$-11.8$],
      [`global_only`], [$bold(+2.51)$], [$bold(+2.81)$], [$bold(+0.44)$], [$bold(+6.14)$], [$bold(+0.96)$], [$+0.49$], [$bold(+0.44)$], [$+7.22$],
      [`norm_only`], [$+0.82$], [$-1.39$], [$-1.90$], [$-5.19$], [$-0.07$], [$+0.38$], [$-4.70$], [$+12.3$],
      [`all_free`], [$+0.73$], [$-2.53$], [$-2.51$], [$-9.56$], [$+0.86$], [$-1.41$], [$-4.43$], [$bold(+16.0)$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[tree (layout)], table.cell(rowspan: 4)[sph], [`all_off`], [$72.0$], [$39.4$], [$123$], [$33.6$], [$39.0$], [$214$], [$54.6$], [$31.6$],
      [`centering_only`], [$+0.01$], [$+0.02$], [$approx 0$], [$+0.03$], [$bold(+0.01)$], [$approx 0$], [$approx 0$], [$approx 0$],
      [`global_only`], [$-1.88$], [$-1.11$], [$-2.85$], [$-1.00$], [$-0.78$], [$-1.51$], [$-6.33$], [$-1.09$],
      [`all_free`], [$bold(+0.01)$], [$bold(+0.03)$], [$approx 0$], [$bold(+0.09)$], [$approx 0$], [$approx 0$], [$approx 0$], [$bold(+0.01)$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[tree (layout)]], table.cell(rowspan: 5)[euc], [`all_off`], [$72.8$], [$39.8$], [$124$], [$34.0$], [$39.1$], [$214$], [$57.8$], [$32.1$],
      [`centering_only`], [$approx 0$], [$approx 0$], [$approx 0$], [$+0.02$], [$-0.01$], [$approx 0$], [$approx 0$], [$approx 0$],
      [`global_only`], [$-0.18$], [$-0.10$], [$-0.28$], [$-0.05$], [$-0.09$], [$-0.09$], [$-0.70$], [$-0.12$],
      [`norm_only`], [$bold(+0.59)$], [$bold(+0.22)$], [$bold(+1.16)$], [$bold(+0.16)$], [$bold(+0.20)$], [$bold(+2.81)$], [$-0.65$], [$bold(+0.18)$],
      [`all_free`], [$+0.40$], [$+0.08$], [$+0.90$], [$+0.13$], [$+0.01$], [$+2.79$], [$-1.41$], [$+0.05$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[tree (layout)]], table.cell(rowspan: 5)[hyp], [`all_off`], [$72.6$], [$39.6$], [$124$], [$33.7$], [$39.1$], [$214$], [$57.3$], [$32.0$],
      [`centering_only`], [$+0.85$], [$+0.25$], [$+1.43$], [$+0.11$], [$approx 0$], [$-0.17$], [$+4.55$], [$+0.54$],
      [`global_only`], [$-0.03$], [$-0.02$], [$-0.04$], [$approx 0$], [$-0.04$], [$-0.08$], [$-0.01$], [$-0.01$],
      [`norm_only`], [$+0.38$], [$+0.14$], [$+0.72$], [$+0.05$], [$+0.13$], [$+1.36$], [$+0.16$], [$+0.15$],
      [`all_free`], [$bold(+3.43)$], [$bold(+1.44)$], [$bold(+5.63)$], [$bold(+1.31)$], [$bold(+0.62)$], [$bold(+2.00)$], [$bold(+13.9)$], [$bold(+2.14)$],
      table.hline(stroke: 0.5pt),
      table.cell(rowspan: 4)[hyp. shells], table.cell(rowspan: 4)[sph], [`all_off`], [$159$], [$128$], [$223$], [$146$], [$118$], [$288$], [$218$], [$103$],
      [`centering_only`], [$bold(+0.27)$], [$-0.63$], [$bold(+0.41)$], [$-2.38$], [$bold(+1.26)$], [$-0.59$], [$bold(+0.67)$], [$bold(+1.87)$],
      [`global_only`], [$-18.3$], [$-8.14$], [$-27.7$], [$-1.14$], [$-13.6$], [$-34.2$], [$-10.7$], [$-13.0$],
      [`all_free`], [$-10.8$], [$-2.87$], [$-17.6$], [$bold(+1.91)$], [$-4.33$], [$-14.9$], [$-9.69$], [$-6.28$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[hyp. shells]], table.cell(rowspan: 5)[euc], [`all_off`], [$171$], [$133$], [$237$], [$154$], [$118$], [$290$], [$229$], [$125$],
      [`centering_only`], [$+10.7$], [$+0.40$], [$+14.0$], [$-3.28$], [$+1.79$], [$+2.02$], [$+10.0$], [$+22.9$],
      [`global_only`], [$+11.7$], [$+1.23$], [$+13.7$], [$-1.14$], [$+1.76$], [$+1.27$], [$+10.0$], [$+29.9$],
      [`norm_only`], [$bold(+37.1)$], [$bold(+6.28)$], [$bold(+63.9)$], [$-1.40$], [$bold(+11.0)$], [$+68.6$], [$bold(+55.4)$], [$+49.3$],
      [`all_free`], [$+36.4$], [$+5.00$], [$+63.3$], [$-2.66$], [$+9.41$], [$bold(+68.7)$], [$+53.9$], [$bold(+49.4)$],
      table.hline(stroke: 0.2pt, start: 1),
      table.cell(rowspan: 5)[#text(fill: luma(40%))[hyp. shells]], table.cell(rowspan: 5)[hyp], [`all_off`], [$160$], [$130$], [$223$], [$154$], [$116$], [$288$], [$219$], [$103$],
      [`centering_only`], [$-23.6$], [$-12.6$], [$-31.0$], [$-4.30$], [$-18.3$], [$-35.4$], [$-12.1$], [$-30.6$],
      [`global_only`], [$-21.3$], [$-12.4$], [$-30.5$], [$-4.35$], [$-20.3$], [$-35.1$], [$-12.4$], [$-13.6$],
      [`norm_only`], [$+15.6$], [$bold(+2.62)$], [$+27.6$], [$-2.30$], [$bold(+8.20)$], [$+57.0$], [$+2.60$], [$+22.3$],
      [`all_free`], [$bold(+34.2)$], [$+2.25$], [$bold(+72.1)$], [$-3.22$], [$+7.64$], [$bold(+72.2)$], [$bold(+99.7)$], [$bold(+31.3)$],
      table.hline(stroke: 0.8pt),
    ),
    caption: [Experiment 4: R2 indicator gain $Delta R_2$ of each loss-weight setting over the
    `all_off` baseline on the synthetic datasets of known intrinsic geometry, under each preference region of @preference-regions
    ($N = 5000$).

    Every entry is multiplied by $1000$, so a table entry of $1$ is an indicator value
    of $10^(-3)$.
    The `all_off` row opening each geometry block is the baseline *level* $R_2$ of that front
    (@eq:r2), a cost: smaller is better.  Every row below it is the *gain*
    $Delta R_2 = R_2("all_off") - R_2("setting")$ of @eq:r2-gain, formed
    baseline-minus-setting so that a positive value means the setting improved on the
    baseline.  Levels are therefore unsigned and gains always carry a sign.
    Within each geometry block the largest positive gain per region is set in bold; a block
    with no positive gain has no bold entry.  An entry of $approx 0$ is a gain below the
    resolution printed here, where the front barely moved and the sign carries nothing.

    The columns are the weight sets of @preference-regions: $W_"all"$ is the full simplex and
    is the only one under which $Delta R_2$ is a claim about overall front quality.  The
    remaining columns each hold the weight vectors placing at least half their mass on a
    stated part of the objective space -- the three *family* columns on that family's two
    objectives, the six *per-objective* columns on that one objective.  A setting that helps
    under one priority and costs under another is visible as a sign change along its row.

    `norm_only` is absent from every spherical block because the depth-norm loss is
    undefined on the sphere (@norm-loss).  `rms_anchored` is not an ablation of a loss term
    and is reported with the curvature results (@curvature-magnitude-results) instead.
  ],
  ) <tab:r2-delta-synthetic-n5000>
]
