// Generated by scripts/three_arm_typst.py -- do not edit by hand.
#figure(
  table(
    columns: 10,
    align: (left, right, right, right, right, right, right, right, right, right),
    stroke: none,
    inset: (x: 2.5pt, y: 4pt),
    table.hline(stroke: 0.8pt),
    table.header(
      [*Dataset*],
      $R_"sph"$, $R_"euc"$, $R_"hyp"$,
      $r^*_"hyp"$, $K_"hyp"$, $kappa_"hyp"$,
      $r^*_"sph"$, $K_"sph"$, $kappa_"sph"$,
    ),
    table.hline(stroke: 0.5pt),
    [grid 10D], [$0.12$], [$0.13$], [$0.13$], [$8.74$#super[†]], [$-0.0131$#super[†]], [$0.0100$#super[†]], [$1.79$#super[†]], [$0.310$#super[†]], [$5.81$#super[†]],
    [grid 2D], [$7.7 dot 10^(-3)$], [$7.7 dot 10^(-16)$], [$1.4 dot 10^(-4)$], [$8.19$#super[†]], [$-0.0149$#super[†]], [$0.0100$#super[†]], [$1.08$#super[†]], [$0.862$#super[†]], [$5.91$#super[†]],
    [sphere 2D], [$3.1 dot 10^(-8)$], [$0.20$], [$0.21$], [$11.3$#super[†]], [$-7.83 dot 10^(-3)$#super[†]], [$0.0100$#super[†]], [$1.00$], [$1.00$], [$3.05$],
    [sphere 10D], [$0.085$], [$0.28$], [$0.28$], [$5.98$#super[†]], [$-0.0279$#super[†]], [$0.0100$#super[†]], [$1.00$], [$1.00$], [$2.99$],
    [tree 2D], [$0.23$], [$0.24$], [$0.24$], [$45.4$#super[†]], [$-4.84 dot 10^(-4)$#super[†]], [$0.0100$#super[†]], [$4.58$], [$0.0476$], [$3.06$],
    [tree 10D], [$0.063$], [$0.067$], [$0.068$], [$38.8$#super[†]], [$-6.66 dot 10^(-4)$#super[†]], [$0.0100$#super[†]], [$7.31$], [$0.0187$], [$5.73$],
    table.hline(stroke: 0.5pt),
    [mnist], [$0.17$], [$0.19$], [$0.19$], [$29.8$#super[†]], [$-1.13 dot 10^(-3)$#super[†]], [$0.0100$#super[†]], [$5.96$#super[†]], [$0.0282$#super[†]], [$2.12$#super[†]],
    [mnist-fashion], [$0.083$], [$0.085$], [$0.085$], [$56.6$#super[†]], [$-3.12 dot 10^(-4)$#super[†]], [$0.0100$#super[†]], [$8.25$#super[†]], [$0.0147$#super[†]], [$5.00$#super[†]],
    [wordnet-mammals], [$0.16$], [$0.17$], [$0.17$], [$33.3$#super[†]], [$-9.02 dot 10^(-4)$#super[†]], [$0.0100$#super[†]], [$3.82$], [$0.0685$], [$3.93$],
    [pbmc], [$0.022$], [$0.024$], [$0.025$], [$71.5$#super[†]], [$-1.96 dot 10^(-4)$#super[†]], [$0.0100$#super[†]], [$26.2$], [$1.46 dot 10^(-3)$], [$8.22$],
    [H2 exact (ctrl)], [$0.16$], [$0.15$], [$1.1 dot 10^(-5)$], [$1.00$], [$-1.00$], [$16.9$], [$3.18$], [$0.0988$], [$3.01$],
    [hyperbolic_shells], [$0.063$], [$0.070$], [$0.071$], [$7.54$#super[†]], [$-0.0176$#super[†]], [$0.0100$#super[†]], [$2.53$], [$0.156$], [$7.77$],
    [antipodal_clusters], [$0.022$], [$0.14$], [$0.14$], [$11.8$#super[†]], [$-7.17 dot 10^(-3)$#super[†]], [$0.0100$#super[†]], [$1.00$], [$1.00$], [$4.22$],
    table.hline(stroke: 0.8pt),
  ),
  caption: [Three-arm Wilson fits of the thesis datasets.
  Each arm fits a two-dimensional constant-curvature model to the dataset's
  pairwise distance matrix ($N = 1000$, target dimension 2, seed 42)
  and reports the normalised signature residual $rho(r^*)$ of @eq:wilson-residual,
  written $R_"sph"$, $R_"euc"$, $R_"hyp"$ and gauged by $n dot d_"max"^2$ so the
  three arms are comparable to one another and across datasets.
  The Euclidean arm is the nested null model rather than a third sibling: it is the
  $r arrow.r infinity$ limit of both curved kernels, so a curved arm can always match it
  by running flat-ward and the question the table answers is whether curvature buys a
  strictly better fit than flat.
  For each curved arm, $r^*$ is the fitted radius, $K = minus.plus 1\/r^(*2)$ the signed
  sectional curvature it implies, and $kappa = |K| dot R_"rms"^2$ its dimensionless form
  (@eq:kappa), where $R_"rms"$ is the RMS geodesic radius of the configuration the fit
  implies.  That configuration is not a further estimate: each $Z(r^*)$ *is* the Gram
  matrix of the model it tests for, so its retained eigen-block is the configuration
  itself.  Gauging $kappa$ this way rather than by the input's $d_"rms"$ puts it on the
  same axis as the $kappa$ every t-SNE trial reports, so the detector's answer and the
  optimiser's can be compared directly.
  Only $kappa$ is comparable across rows: $r^*$ and $K$ carry the units of the input
  distance matrix, which are pixel distances for MNIST and Fashion-MNIST, principal-component
  distances for PBMC, and graph hops for WordNet mammals.
  The suffixes follow the dataset labels and are not one convention: for `sphere` and `tree`,
  2D is the intrinsic dimension ($S^2$ and a tree in $H^2$, both in $RR^3$) while 10D is the
  ambient one ($S^9$ and $H^9$ in $RR^(10)$); for `grid` the two coincide.
  A dagger marks a fit pinned on the flat-ward edge of its search window, where the
  reported value is the bound and not a measurement.
  The hyperbolic search is capped at the radius where the implied configuration's
  $kappa$ falls to $kappa_"min" = 0.01$, so a pinned hyperbolic arm reports exactly
  $kappa_"hyp" = 0.01$ --- the cap is a bound on the very quantity the column shows.
  Beyond that radius the model is flat to within a fifth of a percent across the
  sample, since a geodesic circle of radius $R_"rms"$ in $H^2(r)$ departs from the
  Euclidean one by a relative $kappa\/6$.
  The spherical search is confined to the angular-coverage window
  $[d_"max"\/pi, d_"max"\/2.5]$, so $r^*_"sph"$ always lies near $0.32$--$0.40 dot d_"max"$
  and pinning at its upper edge means the data prefers a flatter model than a well-covered
  sphere --- the signal on which a spherical verdict is rejected.
  ],
) <tab:geometry-inference>
