"""
Turn the JSONL emitted by `crates/core/examples/three_arm_residuals.rs` into a
Typst `#figure(table(...))` fragment for the thesis.

Usage:
    uv run python scripts/three_arm_typst.py \
        --input three_arm_residuals.jsonl \
        --output three_arm_residuals.typ

The fragment is self-contained: numbers are pre-rendered as Typst math, so it
needs no package imports beyond what `docs/thesis/main.typ` already provides,
and it can be `#include`d wherever `<tab:geometry-inference>` is referenced.

Stdlib only.
"""

import argparse
import json
import math

# Table order. Rows absent from the JSONL are skipped; rows present but not
# listed here are appended at the end, so `--all` runs still produce output.
ROW_ORDER = [
    "grid 10D",
    "grid 2D",
    "sphere 2D",
    "sphere 10D",
    "tree 2D",
    "tree 10D",
    "mnist",
    "mnist-fashion",
    "wordnet-mammals",
    "pbmc",
]

# Where the rule separating synthetic from real datasets goes.
FIRST_REAL = "mnist"

# Marks a fit that came to rest on the flat-ward edge of its search window.
# Such a value is the bound, not a measurement, and the caption says so.
PINNED_MARK = "#super[†]"


def sci(x: float, sig: int) -> str:
    """Render `x` as Typst math in scientific notation with `sig` significant
    figures.  Exponents in [-2, 2] are written plainly instead, since
    `0.0100` reads better than `1.00 dot 10^(-2)` in a table cell."""
    if x is None or not math.isfinite(x):
        return "---"
    if x == 0.0:
        return "$0$"
    exp = math.floor(math.log10(abs(x)))
    # Rounding to `sig` figures can carry into the next decade: the hyperbolic
    # search bound comes back as 0.00999999..., whose exponent is -3 and whose
    # mantissa then rounds to 10.00.  Renormalise so the mantissa stays in
    # [1, 10) and the value prints as the 0.0100 it is.
    if abs(round(x / (10.0**exp), sig - 1)) >= 10.0:
        exp += 1
    if -2 <= exp <= 2:
        decimals = max(sig - 1 - exp, 0)
        return f"${x:.{decimals}f}$"
    mantissa = x / (10.0**exp)
    return f"${mantissa:.{sig - 1}f} dot 10^({exp})$"


def cell(text: str, pinned: bool) -> str:
    return f"[{text}{PINNED_MARK}]" if pinned else f"[{text}]"


def build(rows: list[dict]) -> str:
    by_name = {r["dataset"]: r for r in rows}
    order = [n for n in ROW_ORDER if n in by_name]
    order += [r["dataset"] for r in rows if r["dataset"] not in ROW_ORDER]

    n_values = sorted({r["n"] for r in rows})
    dims = sorted({r["dim"] for r in rows})
    seeds = sorted({r["seed"] for r in rows})
    n_desc = ", ".join(str(v) for v in n_values)
    dim_desc = ", ".join(str(v) for v in dims)
    seed_desc = ", ".join(str(v) for v in seeds)

    any_pinned = any(r["hyp_pinned"] or r["sph_pinned"] for r in rows)

    lines = [
        "// Generated by scripts/three_arm_typst.py -- do not edit by hand.",
        "#figure(",
        "  table(",
        "    columns: 10,",
        "    align: (left, right, right, right, right, right, right, right, right, right),",
        "    stroke: none,",
        # Ten columns at the default 5pt side inset spend ~3.5cm of the text
        # width on padding, which wraps the scientific-notation cells onto a
        # second line. Same treatment as the hand-written table in `5results.typ`.
        "    inset: (x: 2.5pt, y: 4pt),",
        "    table.hline(stroke: 0.8pt),",
        "    table.header(",
        "      [*Dataset*],",
        "      $R_\"sph\"$, $R_\"euc\"$, $R_\"hyp\"$,",
        "      $r^*_\"hyp\"$, $K_\"hyp\"$, $kappa_\"hyp\"$,",
        "      $r^*_\"sph\"$, $K_\"sph\"$, $kappa_\"sph\"$,",
        "    ),",
        "    table.hline(stroke: 0.5pt),",
    ]

    for name in order:
        r = by_name[name]
        if name == FIRST_REAL:
            lines.append("    table.hline(stroke: 0.5pt),")
        hp, sp = r["hyp_pinned"], r["sph_pinned"]
        cells = [
            f"[{name}]",
            f"[{sci(r['r_sph'], 2)}]",
            f"[{sci(r['r_euc'], 2)}]",
            f"[{sci(r['r_hyp'], 2)}]",
            cell(sci(r["r_star_hyp"], 3), hp),
            cell(sci(r["k_hyp"], 3), hp),
            cell(sci(r["kappa_hyp"], 3), hp),
            cell(sci(r["r_star_sph"], 3), sp),
            cell(sci(r["k_sph"], 3), sp),
            cell(sci(r["kappa_sph"], 3), sp),
        ]
        lines.append("    " + ", ".join(cells) + ",")

    lines.append("    table.hline(stroke: 0.8pt),")
    lines.append("  ),")

    caption = [
        "  caption: [Three-arm Wilson fits of the thesis datasets.",
        "  Each arm fits a two-dimensional constant-curvature model to the dataset's",
        f"  pairwise distance matrix ($N = {n_desc}$, target dimension {dim_desc}, seed {seed_desc})",
        "  and reports the normalised signature residual $rho(r^*)$ of @eq:wilson-residual,",
        "  written $R_\"sph\"$, $R_\"euc\"$, $R_\"hyp\"$ and gauged by $n dot d_\"max\"^2$ so the",
        "  three arms are comparable to one another and across datasets.",
        "  The Euclidean arm is the nested null model rather than a third sibling: it is the",
        "  $r arrow.r infinity$ limit of both curved kernels, so a curved arm can always match it",
        "  by running flat-ward and the question the table answers is whether curvature buys a",
        "  strictly better fit than flat.",
        "  For each curved arm, $r^*$ is the fitted radius, $K = minus.plus 1\\/r^(*2)$ the signed",
        "  sectional curvature it implies, and $kappa = |K| dot R_\"rms\"^2$ its dimensionless form",
        "  (@eq:kappa), where $R_\"rms\"$ is the RMS geodesic radius of the configuration the fit",
        "  implies.  That configuration is not a further estimate: each $Z(r^*)$ *is* the Gram",
        "  matrix of the model it tests for, so its retained eigen-block is the configuration",
        "  itself.  Gauging $kappa$ this way rather than by the input's $d_\"rms\"$ puts it on the",
        "  same axis as the $kappa$ every t-SNE trial reports, so the detector's answer and the",
        "  optimiser's can be compared directly.",
        "  Only $kappa$ is comparable across rows: $r^*$ and $K$ carry the units of the input",
        "  distance matrix, which are pixel distances for MNIST and Fashion-MNIST, principal-component",
        "  distances for PBMC, and graph hops for WordNet mammals.",
        "  The suffixes follow the dataset labels and are not one convention: for `sphere` and `tree`,",
        "  2D is the intrinsic dimension ($S^2$ and a tree in $H^2$, both in $RR^3$) while 10D is the",
        "  ambient one ($S^9$ and $H^9$ in $RR^(10)$); for `grid` the two coincide.",
    ]
    if any_pinned:
        caption += [
            "  A dagger marks a fit pinned on the flat-ward edge of its search window, where the",
            "  reported value is the bound and not a measurement.",
            "  The hyperbolic search is capped at the radius where the implied configuration's",
            "  $kappa$ falls to $kappa_\"min\" = 0.01$, so a pinned hyperbolic arm reports exactly",
            "  $kappa_\"hyp\" = 0.01$ --- the cap is a bound on the very quantity the column shows.",
            "  Beyond that radius the model is flat to within a fifth of a percent across the",
            "  sample, since a geodesic circle of radius $R_\"rms\"$ in $H^2(r)$ departs from the",
            "  Euclidean one by a relative $kappa\\/6$.",
            "  The spherical search is confined to the angular-coverage window",
            "  $[d_\"max\"\\/pi, d_\"max\"\\/2.5]$, so $r^*_\"sph\"$ always lies near $0.32$--$0.40 dot d_\"max\"$",
            "  and pinning at its upper edge means the data prefers a flatter model than a well-covered",
            "  sphere --- the signal on which a spherical verdict is rejected.",
        ]
    caption.append("  ],")
    lines += caption

    lines.append(") <tab:geometry-inference>")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", default="three_arm_residuals.jsonl")
    ap.add_argument("--output", default="three_arm_residuals.typ")
    a = ap.parse_args()

    with open(a.input) as f:
        rows = [json.loads(line) for line in f if line.strip()]
    if not rows:
        raise SystemExit(f"{a.input} is empty")

    with open(a.output, "w") as f:
        f.write(build(rows))
    print(f"wrote {len(rows)} rows to {a.output}")


if __name__ == "__main__":
    main()
